# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_link_request_callback_parameters import PaymentLinkRequestCallbackParameters

class TestPaymentLinkRequestCallbackParameters(unittest.TestCase):
    """PaymentLinkRequestCallbackParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkRequestCallbackParameters:
        """Test PaymentLinkRequestCallbackParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkRequestCallbackParameters`
        """
        model = PaymentLinkRequestCallbackParameters()
        if include_optional:
            return PaymentLinkRequestCallbackParameters(
                callback_api_url = '',
                callback_message = '',
                callback_success_url = '',
                callback_failure_url = '',
                access_key = '',
                secret_key = '',
                reference_no = '',
                reference_type = '',
                transaction_id = '',
                redirection_time = 56
            )
        else:
            return PaymentLinkRequestCallbackParameters(
        )
        """

    def testPaymentLinkRequestCallbackParameters(self):
        """Test PaymentLinkRequestCallbackParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
