# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_endorsement_request_quote_details import PFEndorsementRequestQuoteDetails

class TestPFEndorsementRequestQuoteDetails(unittest.TestCase):
    """PFEndorsementRequestQuoteDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFEndorsementRequestQuoteDetails:
        """Test PFEndorsementRequestQuoteDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFEndorsementRequestQuoteDetails`
        """
        model = PFEndorsementRequestQuoteDetails()
        if include_optional:
            return PFEndorsementRequestQuoteDetails(
                commercial = '',
                coupon = '',
                coupon_invoice_printed = True,
                crd = 1.337,
                interval = '',
                installments = 1.337,
                program_id = 1.337,
                broker_fee = 1.337,
                e_sign_option = '',
                process_down_payment = True,
                process_down_payment_no_reason = '',
                down_payment_method = '',
                down_payment_paid_by = '',
                batch_id = '',
                return_pfa = True,
                equal_payments = '',
                quote_expiration_days = 1.337,
                bypass_cadnb = True,
                allow_zero_apr = True,
                associated_account_number = '',
                channel = '',
                channel_version = ''
            )
        else:
            return PFEndorsementRequestQuoteDetails(
        )
        """

    def testPFEndorsementRequestQuoteDetails(self):
        """Test PFEndorsementRequestQuoteDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
