# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_link_response_display_settings import PaymentLinkResponseDisplaySettings

class TestPaymentLinkResponseDisplaySettings(unittest.TestCase):
    """PaymentLinkResponseDisplaySettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkResponseDisplaySettings:
        """Test PaymentLinkResponseDisplaySettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkResponseDisplaySettings`
        """
        model = PaymentLinkResponseDisplaySettings()
        if include_optional:
            return PaymentLinkResponseDisplaySettings(
                selected_customer_fields = '',
                additional_details_preference = 'AskShopper',
                display_summary = True,
                accept_customer_info = True,
                remove_header = True,
                accept_card = True,
                accept_bank_account = True,
                save_customer = True,
                save_customer_account = True,
                intent = openapi_client.models.payment_link_response_display_settings_intent.PaymentLinkResponse_displaySettings_intent(
                    payment_types = [
                        'NotDefined'
                        ], )
            )
        else:
            return PaymentLinkResponseDisplaySettings(
        )
        """

    def testPaymentLinkResponseDisplaySettings(self):
        """Test PaymentLinkResponseDisplaySettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
