# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_policy_update_request_dto import PFPolicyUpdateRequestDTO

class TestPFPolicyUpdateRequestDTO(unittest.TestCase):
    """PFPolicyUpdateRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFPolicyUpdateRequestDTO:
        """Test PFPolicyUpdateRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFPolicyUpdateRequestDTO`
        """
        model = PFPolicyUpdateRequestDTO()
        if include_optional:
            return PFPolicyUpdateRequestDTO(
                quote_key = 1.337,
                account_number = '',
                premium = 1.337,
                category = '',
                new_policy_number = ''
            )
        else:
            return PFPolicyUpdateRequestDTO(
                quote_key = 1.337,
                premium = 1.337,
                category = '',
                new_policy_number = '',
        )
        """

    def testPFPolicyUpdateRequestDTO(self):
        """Test PFPolicyUpdateRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
