# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_endorsement_request_quote_policies_inner_total_pay_funding_inner import PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner

class TestPFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner(unittest.TestCase):
    """PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner:
        """Test PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner`
        """
        model = PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner()
        if include_optional:
            return PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner(
                pay_to = '',
                payment_method = '',
                funding_type = '',
                bank_routing_number = '',
                bank_acct_number = '',
                is_checking_account = True,
                amount = 1.337,
                funding_date = ''
            )
        else:
            return PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner(
        )
        """

    def testPFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner(self):
        """Test PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
