# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_lite_secure_quote_request_policies_inner import PFLiteSecureQuoteRequestPoliciesInner

class TestPFLiteSecureQuoteRequestPoliciesInner(unittest.TestCase):
    """PFLiteSecureQuoteRequestPoliciesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFLiteSecureQuoteRequestPoliciesInner:
        """Test PFLiteSecureQuoteRequestPoliciesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFLiteSecureQuoteRequestPoliciesInner`
        """
        model = PFLiteSecureQuoteRequestPoliciesInner()
        if include_optional:
            return PFLiteSecureQuoteRequestPoliciesInner(
                id = '',
                policy_number = '',
                premium = 1.337,
                coverage_type = '',
                effective_date = '',
                minimum_earned_percent = 1.337,
                carrier = openapi_client.models.pf_lite_secure_quote_request_policies_inner_carrier.PFLiteSecureQuoteRequest_policies_inner_carrier(
                    name = '', 
                    best_number = '', 
                    unique_id = '', )
            )
        else:
            return PFLiteSecureQuoteRequestPoliciesInner(
                policy_number = '',
                effective_date = '',
                minimum_earned_percent = 1.337,
        )
        """

    def testPFLiteSecureQuoteRequestPoliciesInner(self):
        """Test PFLiteSecureQuoteRequestPoliciesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
