# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_link_request_settings import PaymentLinkRequestSettings

class TestPaymentLinkRequestSettings(unittest.TestCase):
    """PaymentLinkRequestSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkRequestSettings:
        """Test PaymentLinkRequestSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkRequestSettings`
        """
        model = PaymentLinkRequestSettings()
        if include_optional:
            return PaymentLinkRequestSettings(
                additional_details_preference = 'AskShopper',
                intent = openapi_client.models.payment_link_request_settings_intent.PaymentLinkRequest_settings_intent(
                    payment_types = [
                        ''
                        ], ),
                selected_customer_fields = '',
                display_summary = True,
                accept_customer_info = True,
                remove_header = True,
                accept_card = True,
                accept_bank_account = True,
                save_customer = True,
                save_customer_account = True
            )
        else:
            return PaymentLinkRequestSettings(
        )
        """

    def testPaymentLinkRequestSettings(self):
        """Test PaymentLinkRequestSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
