# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_lite_secure_quote_request_program import PFLiteSecureQuoteRequestProgram

class TestPFLiteSecureQuoteRequestProgram(unittest.TestCase):
    """PFLiteSecureQuoteRequestProgram unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFLiteSecureQuoteRequestProgram:
        """Test PFLiteSecureQuoteRequestProgram
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFLiteSecureQuoteRequestProgram`
        """
        model = PFLiteSecureQuoteRequestProgram()
        if include_optional:
            return PFLiteSecureQuoteRequestProgram(
                program_id = 1.337,
                loan_type = 'Commercial'
            )
        else:
            return PFLiteSecureQuoteRequestProgram(
                program_id = 1.337,
                loan_type = 'Commercial',
        )
        """

    def testPFLiteSecureQuoteRequestProgram(self):
        """Test PFLiteSecureQuoteRequestProgram"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
