# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_retrieve_pfa_request_dto import PFRetrievePFARequestDTO

class TestPFRetrievePFARequestDTO(unittest.TestCase):
    """PFRetrievePFARequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFRetrievePFARequestDTO:
        """Test PFRetrievePFARequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFRetrievePFARequestDTO`
        """
        model = PFRetrievePFARequestDTO()
        if include_optional:
            return PFRetrievePFARequestDTO(
                quote_key = '',
                merchant_token = ''
            )
        else:
            return PFRetrievePFARequestDTO(
        )
        """

    def testPFRetrievePFARequestDTO(self):
        """Test PFRetrievePFARequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
