# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secure_token_link_response_customers_inner import SecureTokenLinkResponseCustomersInner

class TestSecureTokenLinkResponseCustomersInner(unittest.TestCase):
    """SecureTokenLinkResponseCustomersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureTokenLinkResponseCustomersInner:
        """Test SecureTokenLinkResponseCustomersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureTokenLinkResponseCustomersInner`
        """
        model = SecureTokenLinkResponseCustomersInner()
        if include_optional:
            return SecureTokenLinkResponseCustomersInner(
                first_name = '',
                last_name = '',
                email = '',
                phone = '',
                address = openapi_client.models.token_link_secure_request_customers_inner_address.TokenLinkSecureRequest_customers_inner_address(
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = 1.337, 
                    postal_code = '', 
                    time_zone = '', )
            )
        else:
            return SecureTokenLinkResponseCustomersInner(
        )
        """

    def testSecureTokenLinkResponseCustomersInner(self):
        """Test SecureTokenLinkResponseCustomersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
