# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.refund_eligibility import RefundEligibility

class TestRefundEligibility(unittest.TestCase):
    """RefundEligibility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundEligibility:
        """Test RefundEligibility
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundEligibility`
        """
        model = RefundEligibility()
        if include_optional:
            return RefundEligibility(
                refund_eligible = True,
                message = ''
            )
        else:
            return RefundEligibility(
        )
        """

    def testRefundEligibility(self):
        """Test RefundEligibility"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
