/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PageVendorResponseDTODataInner
    /// </summary>
    [DataContract(Name = "PageVendorResponseDTO_data_inner")]
    public partial class PageVendorResponseDTODataInner : IValidatableObject
    {
        /// <summary>
        /// Defines LegalEntityType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LegalEntityTypeEnum
        {
            /// <summary>
            /// Enum NA for value: NA
            /// </summary>
            [EnumMember(Value = "NA")]
            NA = 1,

            /// <summary>
            /// Enum Corporation for value: Corporation
            /// </summary>
            [EnumMember(Value = "Corporation")]
            Corporation = 2,

            /// <summary>
            /// Enum LimitedLiabilityCompany for value: LimitedLiabilityCompany
            /// </summary>
            [EnumMember(Value = "LimitedLiabilityCompany")]
            LimitedLiabilityCompany = 3,

            /// <summary>
            /// Enum LimitedLiabilityPartnership for value: LimitedLiabilityPartnership
            /// </summary>
            [EnumMember(Value = "LimitedLiabilityPartnership")]
            LimitedLiabilityPartnership = 4,

            /// <summary>
            /// Enum LimitedPartnership for value: LimitedPartnership
            /// </summary>
            [EnumMember(Value = "LimitedPartnership")]
            LimitedPartnership = 5,

            /// <summary>
            /// Enum Partnership for value: Partnership
            /// </summary>
            [EnumMember(Value = "Partnership")]
            Partnership = 6,

            /// <summary>
            /// Enum Individual for value: Individual
            /// </summary>
            [EnumMember(Value = "Individual")]
            Individual = 7
        }


        /// <summary>
        /// Gets or Sets LegalEntityType
        /// </summary>
        [DataMember(Name = "legalEntityType", EmitDefaultValue = false)]
        public LegalEntityTypeEnum? LegalEntityType { get; set; }
        /// <summary>
        /// Defines PaymentMethodType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PaymentMethodTypeEnum
        {
            /// <summary>
            /// Enum Check for value: Check
            /// </summary>
            [EnumMember(Value = "Check")]
            Check = 1
        }


        /// <summary>
        /// Gets or Sets PaymentMethodType
        /// </summary>
        [DataMember(Name = "paymentMethodType", EmitDefaultValue = false)]
        public PaymentMethodTypeEnum? PaymentMethodType { get; set; }
        /// <summary>
        /// Defines VendorStatus
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VendorStatusEnum
        {
            /// <summary>
            /// Enum NA for value: NA
            /// </summary>
            [EnumMember(Value = "NA")]
            NA = 1,

            /// <summary>
            /// Enum Reviewing for value: Reviewing
            /// </summary>
            [EnumMember(Value = "Reviewing")]
            Reviewing = 2,

            /// <summary>
            /// Enum Approved for value: Approved
            /// </summary>
            [EnumMember(Value = "Approved")]
            Approved = 3,

            /// <summary>
            /// Enum Denied for value: Denied
            /// </summary>
            [EnumMember(Value = "Denied")]
            Denied = 4,

            /// <summary>
            /// Enum Suspended for value: Suspended
            /// </summary>
            [EnumMember(Value = "Suspended")]
            Suspended = 5,

            /// <summary>
            /// Enum Deleted for value: Deleted
            /// </summary>
            [EnumMember(Value = "Deleted")]
            Deleted = 6
        }


        /// <summary>
        /// Gets or Sets VendorStatus
        /// </summary>
        [DataMember(Name = "vendorStatus", EmitDefaultValue = false)]
        public VendorStatusEnum? VendorStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PageVendorResponseDTODataInner" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="paymentBasedId">paymentBasedId.</param>
        /// <param name="legalEntityType">legalEntityType.</param>
        /// <param name="merchantId">merchantId.</param>
        /// <param name="vendorName">vendorName.</param>
        /// <param name="vendorAliasName">vendorAliasName.</param>
        /// <param name="vendorDbName">vendorDbName.</param>
        /// <param name="paymentMethodType">paymentMethodType.</param>
        /// <param name="notificationType">notificationType.</param>
        /// <param name="vendorNotes">vendorNotes.</param>
        /// <param name="phoneNumber">phoneNumber.</param>
        /// <param name="isMobileNumber">isMobileNumber.</param>
        /// <param name="email">email.</param>
        /// <param name="url">url.</param>
        /// <param name="vendorStatus">vendorStatus.</param>
        /// <param name="useSameAsPhysicalAddress">useSameAsPhysicalAddress.</param>
        /// <param name="physicalAddress">physicalAddress.</param>
        /// <param name="remittanceAddress">remittanceAddress.</param>
        /// <param name="verificationResults">verificationResults.</param>
        /// <param name="createdBy">createdBy.</param>
        /// <param name="modifiedBy">modifiedBy.</param>
        /// <param name="createdOn">createdOn.</param>
        /// <param name="modifiedOn">modifiedOn.</param>
        /// <param name="approvedDate">approvedDate.</param>
        /// <param name="template">template.</param>
        public PageVendorResponseDTODataInner(string id = default(string), string paymentBasedId = default(string), LegalEntityTypeEnum? legalEntityType = default(LegalEntityTypeEnum?), string merchantId = default(string), string vendorName = default(string), string vendorAliasName = default(string), string vendorDbName = default(string), PaymentMethodTypeEnum? paymentMethodType = default(PaymentMethodTypeEnum?), string notificationType = default(string), string vendorNotes = default(string), string phoneNumber = default(string), bool isMobileNumber = default(bool), string email = default(string), string url = default(string), VendorStatusEnum? vendorStatus = default(VendorStatusEnum?), bool useSameAsPhysicalAddress = default(bool), VendorResponseDTORemittanceAddress physicalAddress = default(VendorResponseDTORemittanceAddress), VendorResponseDTORemittanceAddress remittanceAddress = default(VendorResponseDTORemittanceAddress), VendorResponseDTOVerificationResultsInner verificationResults = default(VendorResponseDTOVerificationResultsInner), string createdBy = default(string), string modifiedBy = default(string), string createdOn = default(string), string modifiedOn = default(string), string approvedDate = default(string), VendorResponseDTOTemplate template = default(VendorResponseDTOTemplate))
        {
            this.Id = id;
            this.PaymentBasedId = paymentBasedId;
            this.LegalEntityType = legalEntityType;
            this.MerchantId = merchantId;
            this.VendorName = vendorName;
            this.VendorAliasName = vendorAliasName;
            this.VendorDbName = vendorDbName;
            this.PaymentMethodType = paymentMethodType;
            this.NotificationType = notificationType;
            this.VendorNotes = vendorNotes;
            this.PhoneNumber = phoneNumber;
            this.IsMobileNumber = isMobileNumber;
            this.Email = email;
            this.Url = url;
            this.VendorStatus = vendorStatus;
            this.UseSameAsPhysicalAddress = useSameAsPhysicalAddress;
            this.PhysicalAddress = physicalAddress;
            this.RemittanceAddress = remittanceAddress;
            this.VerificationResults = verificationResults;
            this.CreatedBy = createdBy;
            this.ModifiedBy = modifiedBy;
            this.CreatedOn = createdOn;
            this.ModifiedOn = modifiedOn;
            this.ApprovedDate = approvedDate;
            this.Template = template;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets PaymentBasedId
        /// </summary>
        [DataMember(Name = "paymentBasedId", EmitDefaultValue = false)]
        public string PaymentBasedId { get; set; }

        /// <summary>
        /// Gets or Sets MerchantId
        /// </summary>
        [DataMember(Name = "merchantId", EmitDefaultValue = false)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Gets or Sets VendorName
        /// </summary>
        [DataMember(Name = "vendorName", EmitDefaultValue = false)]
        public string VendorName { get; set; }

        /// <summary>
        /// Gets or Sets VendorAliasName
        /// </summary>
        [DataMember(Name = "vendorAliasName", EmitDefaultValue = false)]
        public string VendorAliasName { get; set; }

        /// <summary>
        /// Gets or Sets VendorDbName
        /// </summary>
        [DataMember(Name = "vendorDbName", EmitDefaultValue = false)]
        public string VendorDbName { get; set; }

        /// <summary>
        /// Gets or Sets NotificationType
        /// </summary>
        [DataMember(Name = "notificationType", EmitDefaultValue = false)]
        public string NotificationType { get; set; }

        /// <summary>
        /// Gets or Sets VendorNotes
        /// </summary>
        [DataMember(Name = "vendorNotes", EmitDefaultValue = false)]
        public string VendorNotes { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumber
        /// </summary>
        [DataMember(Name = "phoneNumber", EmitDefaultValue = false)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or Sets IsMobileNumber
        /// </summary>
        [DataMember(Name = "isMobileNumber", EmitDefaultValue = true)]
        public bool IsMobileNumber { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets UseSameAsPhysicalAddress
        /// </summary>
        [DataMember(Name = "useSameAsPhysicalAddress", EmitDefaultValue = true)]
        public bool UseSameAsPhysicalAddress { get; set; }

        /// <summary>
        /// Gets or Sets PhysicalAddress
        /// </summary>
        [DataMember(Name = "physicalAddress", EmitDefaultValue = false)]
        public VendorResponseDTORemittanceAddress PhysicalAddress { get; set; }

        /// <summary>
        /// Gets or Sets RemittanceAddress
        /// </summary>
        [DataMember(Name = "remittanceAddress", EmitDefaultValue = false)]
        public VendorResponseDTORemittanceAddress RemittanceAddress { get; set; }

        /// <summary>
        /// Gets or Sets VerificationResults
        /// </summary>
        [DataMember(Name = "verificationResults", EmitDefaultValue = false)]
        public VendorResponseDTOVerificationResultsInner VerificationResults { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name = "createdBy", EmitDefaultValue = false)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedBy
        /// </summary>
        [DataMember(Name = "modifiedBy", EmitDefaultValue = false)]
        public string ModifiedBy { get; set; }

        /// <summary>
        /// Gets or Sets CreatedOn
        /// </summary>
        [DataMember(Name = "createdOn", EmitDefaultValue = false)]
        public string CreatedOn { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedOn
        /// </summary>
        [DataMember(Name = "modifiedOn", EmitDefaultValue = false)]
        public string ModifiedOn { get; set; }

        /// <summary>
        /// Gets or Sets ApprovedDate
        /// </summary>
        [DataMember(Name = "approvedDate", EmitDefaultValue = false)]
        public string ApprovedDate { get; set; }

        /// <summary>
        /// Gets or Sets Template
        /// </summary>
        [DataMember(Name = "template", EmitDefaultValue = false)]
        public VendorResponseDTOTemplate Template { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PageVendorResponseDTODataInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PaymentBasedId: ").Append(PaymentBasedId).Append("\n");
            sb.Append("  LegalEntityType: ").Append(LegalEntityType).Append("\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  VendorName: ").Append(VendorName).Append("\n");
            sb.Append("  VendorAliasName: ").Append(VendorAliasName).Append("\n");
            sb.Append("  VendorDbName: ").Append(VendorDbName).Append("\n");
            sb.Append("  PaymentMethodType: ").Append(PaymentMethodType).Append("\n");
            sb.Append("  NotificationType: ").Append(NotificationType).Append("\n");
            sb.Append("  VendorNotes: ").Append(VendorNotes).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  IsMobileNumber: ").Append(IsMobileNumber).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  VendorStatus: ").Append(VendorStatus).Append("\n");
            sb.Append("  UseSameAsPhysicalAddress: ").Append(UseSameAsPhysicalAddress).Append("\n");
            sb.Append("  PhysicalAddress: ").Append(PhysicalAddress).Append("\n");
            sb.Append("  RemittanceAddress: ").Append(RemittanceAddress).Append("\n");
            sb.Append("  VerificationResults: ").Append(VerificationResults).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  ModifiedBy: ").Append(ModifiedBy).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  ModifiedOn: ").Append(ModifiedOn).Append("\n");
            sb.Append("  ApprovedDate: ").Append(ApprovedDate).Append("\n");
            sb.Append("  Template: ").Append(Template).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
