/*
 * Secure API
 *
 * Secure API's
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PaymentDetailsResponse
    /// </summary>
    [DataContract(Name = "PaymentDetailsResponse")]
    public partial class PaymentDetailsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentDetailsResponse" /> class.
        /// </summary>
        /// <param name="transactionId">transactionId.</param>
        /// <param name="transactionCode">transactionCode.</param>
        /// <param name="transactionOrigin">transactionOrigin.</param>
        /// <param name="refundOrigin">refundOrigin.</param>
        /// <param name="billingContact">billingContact.</param>
        /// <param name="referenceTransactionId">referenceTransactionId.</param>
        /// <param name="transactionDate">transactionDate.</param>
        /// <param name="merchantId">merchantId.</param>
        /// <param name="ipAddress">ipAddress.</param>
        /// <param name="operationType">operationType.</param>
        /// <param name="channelType">channelType.</param>
        /// <param name="processMethod">processMethod.</param>
        /// <param name="paymentType">paymentType.</param>
        /// <param name="paymentCategory">paymentCategory.</param>
        /// <param name="processorName">processorName.</param>
        /// <param name="tenderInfo">tenderInfo.</param>
        /// <param name="referenceCustomerId">referenceCustomerId.</param>
        /// <param name="customerAccountId">customerAccountId.</param>
        /// <param name="invoiceNo">invoiceNo.</param>
        /// <param name="referenceNo">referenceNo.</param>
        /// <param name="remarks">remarks.</param>
        /// <param name="terminalId">terminalId.</param>
        /// <param name="transactionStatus">transactionStatus.</param>
        /// <param name="previousTransactionStatus">previousTransactionStatus.</param>
        /// <param name="transactionResult">transactionResult.</param>
        /// <param name="invoiceId">invoiceId.</param>
        /// <param name="additionalFields">additionalFields.</param>
        /// <param name="settlementDate">settlementDate.</param>
        /// <param name="issuer">issuer.</param>
        /// <param name="merchantName">merchantName.</param>
        /// <param name="merchantDBAName">merchantDBAName.</param>
        /// <param name="splits">splits.</param>
        /// <param name="paymentDescription">paymentDescription.</param>
        /// <param name="refundTransactions">refundTransactions.</param>
        /// <param name="totalRefundAmount">totalRefundAmount.</param>
        /// <param name="remainingAmount">remainingAmount.</param>
        /// <param name="chargebackReason">chargebackReason.</param>
        /// <param name="chargebackReasonCode">chargebackReasonCode.</param>
        /// <param name="chargebackDateTime">chargebackDateTime.</param>
        /// <param name="subTotalAmount">subTotalAmount.</param>
        /// <param name="companyName">companyName.</param>
        public PaymentDetailsResponse(string transactionId = default(string), string transactionCode = default(string), string transactionOrigin = default(string), string refundOrigin = default(string), SecurePaymentRequestBillingContact billingContact = default(SecurePaymentRequestBillingContact), string referenceTransactionId = default(string), string transactionDate = default(string), string merchantId = default(string), string ipAddress = default(string), string operationType = default(string), string channelType = default(string), string processMethod = default(string), string paymentType = default(string), string paymentCategory = default(string), string processorName = default(string), PaymentDetailsResponseTenderInfo tenderInfo = default(PaymentDetailsResponseTenderInfo), string referenceCustomerId = default(string), string customerAccountId = default(string), string invoiceNo = default(string), string referenceNo = default(string), string remarks = default(string), string terminalId = default(string), string transactionStatus = default(string), string previousTransactionStatus = default(string), PaymentDetailsResponseTransactionResult transactionResult = default(PaymentDetailsResponseTransactionResult), string invoiceId = default(string), string additionalFields = default(string), string settlementDate = default(string), string issuer = default(string), string merchantName = default(string), string merchantDBAName = default(string), string splits = default(string), string paymentDescription = default(string), string refundTransactions = default(string), decimal totalRefundAmount = default(decimal), decimal remainingAmount = default(decimal), string chargebackReason = default(string), string chargebackReasonCode = default(string), string chargebackDateTime = default(string), decimal subTotalAmount = default(decimal), string companyName = default(string))
        {
            this.TransactionId = transactionId;
            this.TransactionCode = transactionCode;
            this.TransactionOrigin = transactionOrigin;
            this.RefundOrigin = refundOrigin;
            this.BillingContact = billingContact;
            this.ReferenceTransactionId = referenceTransactionId;
            this.TransactionDate = transactionDate;
            this.MerchantId = merchantId;
            this.IpAddress = ipAddress;
            this.OperationType = operationType;
            this.ChannelType = channelType;
            this.ProcessMethod = processMethod;
            this.PaymentType = paymentType;
            this.PaymentCategory = paymentCategory;
            this.ProcessorName = processorName;
            this.TenderInfo = tenderInfo;
            this.ReferenceCustomerId = referenceCustomerId;
            this.CustomerAccountId = customerAccountId;
            this.InvoiceNo = invoiceNo;
            this.ReferenceNo = referenceNo;
            this.Remarks = remarks;
            this.TerminalId = terminalId;
            this.TransactionStatus = transactionStatus;
            this.PreviousTransactionStatus = previousTransactionStatus;
            this.TransactionResult = transactionResult;
            this.InvoiceId = invoiceId;
            this.AdditionalFields = additionalFields;
            this.SettlementDate = settlementDate;
            this.Issuer = issuer;
            this.MerchantName = merchantName;
            this.MerchantDBAName = merchantDBAName;
            this.Splits = splits;
            this.PaymentDescription = paymentDescription;
            this.RefundTransactions = refundTransactions;
            this.TotalRefundAmount = totalRefundAmount;
            this.RemainingAmount = remainingAmount;
            this.ChargebackReason = chargebackReason;
            this.ChargebackReasonCode = chargebackReasonCode;
            this.ChargebackDateTime = chargebackDateTime;
            this.SubTotalAmount = subTotalAmount;
            this.CompanyName = companyName;
        }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transactionId", EmitDefaultValue = false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets TransactionCode
        /// </summary>
        [DataMember(Name = "transactionCode", EmitDefaultValue = false)]
        public string TransactionCode { get; set; }

        /// <summary>
        /// Gets or Sets TransactionOrigin
        /// </summary>
        [DataMember(Name = "transactionOrigin", EmitDefaultValue = false)]
        public string TransactionOrigin { get; set; }

        /// <summary>
        /// Gets or Sets RefundOrigin
        /// </summary>
        [DataMember(Name = "refundOrigin", EmitDefaultValue = false)]
        public string RefundOrigin { get; set; }

        /// <summary>
        /// Gets or Sets BillingContact
        /// </summary>
        [DataMember(Name = "billingContact", EmitDefaultValue = false)]
        public SecurePaymentRequestBillingContact BillingContact { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceTransactionId
        /// </summary>
        [DataMember(Name = "referenceTransactionId", EmitDefaultValue = false)]
        public string ReferenceTransactionId { get; set; }

        /// <summary>
        /// Gets or Sets TransactionDate
        /// </summary>
        [DataMember(Name = "transactionDate", EmitDefaultValue = false)]
        public string TransactionDate { get; set; }

        /// <summary>
        /// Gets or Sets MerchantId
        /// </summary>
        [DataMember(Name = "merchantId", EmitDefaultValue = false)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Gets or Sets IpAddress
        /// </summary>
        [DataMember(Name = "ipAddress", EmitDefaultValue = false)]
        public string IpAddress { get; set; }

        /// <summary>
        /// Gets or Sets OperationType
        /// </summary>
        [DataMember(Name = "operationType", EmitDefaultValue = false)]
        public string OperationType { get; set; }

        /// <summary>
        /// Gets or Sets ChannelType
        /// </summary>
        [DataMember(Name = "channelType", EmitDefaultValue = false)]
        public string ChannelType { get; set; }

        /// <summary>
        /// Gets or Sets ProcessMethod
        /// </summary>
        [DataMember(Name = "processMethod", EmitDefaultValue = false)]
        public string ProcessMethod { get; set; }

        /// <summary>
        /// Gets or Sets PaymentType
        /// </summary>
        [DataMember(Name = "paymentType", EmitDefaultValue = false)]
        public string PaymentType { get; set; }

        /// <summary>
        /// Gets or Sets PaymentCategory
        /// </summary>
        [DataMember(Name = "paymentCategory", EmitDefaultValue = false)]
        public string PaymentCategory { get; set; }

        /// <summary>
        /// Gets or Sets ProcessorName
        /// </summary>
        [DataMember(Name = "processorName", EmitDefaultValue = false)]
        public string ProcessorName { get; set; }

        /// <summary>
        /// Gets or Sets TenderInfo
        /// </summary>
        [DataMember(Name = "tenderInfo", EmitDefaultValue = false)]
        public PaymentDetailsResponseTenderInfo TenderInfo { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceCustomerId
        /// </summary>
        [DataMember(Name = "referenceCustomerId", EmitDefaultValue = false)]
        public string ReferenceCustomerId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerAccountId
        /// </summary>
        [DataMember(Name = "customerAccountId", EmitDefaultValue = false)]
        public string CustomerAccountId { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceNo
        /// </summary>
        [DataMember(Name = "invoiceNo", EmitDefaultValue = false)]
        public string InvoiceNo { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceNo
        /// </summary>
        [DataMember(Name = "referenceNo", EmitDefaultValue = false)]
        public string ReferenceNo { get; set; }

        /// <summary>
        /// Gets or Sets Remarks
        /// </summary>
        [DataMember(Name = "remarks", EmitDefaultValue = false)]
        public string Remarks { get; set; }

        /// <summary>
        /// Gets or Sets TerminalId
        /// </summary>
        [DataMember(Name = "terminalId", EmitDefaultValue = false)]
        public string TerminalId { get; set; }

        /// <summary>
        /// Gets or Sets TransactionStatus
        /// </summary>
        [DataMember(Name = "transactionStatus", EmitDefaultValue = false)]
        public string TransactionStatus { get; set; }

        /// <summary>
        /// Gets or Sets PreviousTransactionStatus
        /// </summary>
        [DataMember(Name = "previousTransactionStatus", EmitDefaultValue = false)]
        public string PreviousTransactionStatus { get; set; }

        /// <summary>
        /// Gets or Sets TransactionResult
        /// </summary>
        [DataMember(Name = "transactionResult", EmitDefaultValue = false)]
        public PaymentDetailsResponseTransactionResult TransactionResult { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceId
        /// </summary>
        [DataMember(Name = "invoiceId", EmitDefaultValue = false)]
        public string InvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalFields
        /// </summary>
        [DataMember(Name = "additionalFields", EmitDefaultValue = false)]
        public string AdditionalFields { get; set; }

        /// <summary>
        /// Gets or Sets SettlementDate
        /// </summary>
        [DataMember(Name = "settlementDate", EmitDefaultValue = false)]
        public string SettlementDate { get; set; }

        /// <summary>
        /// Gets or Sets Issuer
        /// </summary>
        [DataMember(Name = "issuer", EmitDefaultValue = false)]
        public string Issuer { get; set; }

        /// <summary>
        /// Gets or Sets MerchantName
        /// </summary>
        [DataMember(Name = "merchantName", EmitDefaultValue = false)]
        public string MerchantName { get; set; }

        /// <summary>
        /// Gets or Sets MerchantDBAName
        /// </summary>
        [DataMember(Name = "merchantDBAName", EmitDefaultValue = false)]
        public string MerchantDBAName { get; set; }

        /// <summary>
        /// Gets or Sets Splits
        /// </summary>
        [DataMember(Name = "splits", EmitDefaultValue = false)]
        public string Splits { get; set; }

        /// <summary>
        /// Gets or Sets PaymentDescription
        /// </summary>
        [DataMember(Name = "paymentDescription", EmitDefaultValue = false)]
        public string PaymentDescription { get; set; }

        /// <summary>
        /// Gets or Sets RefundTransactions
        /// </summary>
        [DataMember(Name = "refundTransactions", EmitDefaultValue = false)]
        public string RefundTransactions { get; set; }

        /// <summary>
        /// Gets or Sets TotalRefundAmount
        /// </summary>
        [DataMember(Name = "totalRefundAmount", EmitDefaultValue = false)]
        public decimal TotalRefundAmount { get; set; }

        /// <summary>
        /// Gets or Sets RemainingAmount
        /// </summary>
        [DataMember(Name = "remainingAmount", EmitDefaultValue = false)]
        public decimal RemainingAmount { get; set; }

        /// <summary>
        /// Gets or Sets ChargebackReason
        /// </summary>
        [DataMember(Name = "chargebackReason", EmitDefaultValue = false)]
        public string ChargebackReason { get; set; }

        /// <summary>
        /// Gets or Sets ChargebackReasonCode
        /// </summary>
        [DataMember(Name = "chargebackReasonCode", EmitDefaultValue = false)]
        public string ChargebackReasonCode { get; set; }

        /// <summary>
        /// Gets or Sets ChargebackDateTime
        /// </summary>
        [DataMember(Name = "chargebackDateTime", EmitDefaultValue = false)]
        public string ChargebackDateTime { get; set; }

        /// <summary>
        /// Gets or Sets SubTotalAmount
        /// </summary>
        [DataMember(Name = "subTotalAmount", EmitDefaultValue = false)]
        public decimal SubTotalAmount { get; set; }

        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>
        [DataMember(Name = "companyName", EmitDefaultValue = false)]
        public string CompanyName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentDetailsResponse {\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  TransactionCode: ").Append(TransactionCode).Append("\n");
            sb.Append("  TransactionOrigin: ").Append(TransactionOrigin).Append("\n");
            sb.Append("  RefundOrigin: ").Append(RefundOrigin).Append("\n");
            sb.Append("  BillingContact: ").Append(BillingContact).Append("\n");
            sb.Append("  ReferenceTransactionId: ").Append(ReferenceTransactionId).Append("\n");
            sb.Append("  TransactionDate: ").Append(TransactionDate).Append("\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  IpAddress: ").Append(IpAddress).Append("\n");
            sb.Append("  OperationType: ").Append(OperationType).Append("\n");
            sb.Append("  ChannelType: ").Append(ChannelType).Append("\n");
            sb.Append("  ProcessMethod: ").Append(ProcessMethod).Append("\n");
            sb.Append("  PaymentType: ").Append(PaymentType).Append("\n");
            sb.Append("  PaymentCategory: ").Append(PaymentCategory).Append("\n");
            sb.Append("  ProcessorName: ").Append(ProcessorName).Append("\n");
            sb.Append("  TenderInfo: ").Append(TenderInfo).Append("\n");
            sb.Append("  ReferenceCustomerId: ").Append(ReferenceCustomerId).Append("\n");
            sb.Append("  CustomerAccountId: ").Append(CustomerAccountId).Append("\n");
            sb.Append("  InvoiceNo: ").Append(InvoiceNo).Append("\n");
            sb.Append("  ReferenceNo: ").Append(ReferenceNo).Append("\n");
            sb.Append("  Remarks: ").Append(Remarks).Append("\n");
            sb.Append("  TerminalId: ").Append(TerminalId).Append("\n");
            sb.Append("  TransactionStatus: ").Append(TransactionStatus).Append("\n");
            sb.Append("  PreviousTransactionStatus: ").Append(PreviousTransactionStatus).Append("\n");
            sb.Append("  TransactionResult: ").Append(TransactionResult).Append("\n");
            sb.Append("  InvoiceId: ").Append(InvoiceId).Append("\n");
            sb.Append("  AdditionalFields: ").Append(AdditionalFields).Append("\n");
            sb.Append("  SettlementDate: ").Append(SettlementDate).Append("\n");
            sb.Append("  Issuer: ").Append(Issuer).Append("\n");
            sb.Append("  MerchantName: ").Append(MerchantName).Append("\n");
            sb.Append("  MerchantDBAName: ").Append(MerchantDBAName).Append("\n");
            sb.Append("  Splits: ").Append(Splits).Append("\n");
            sb.Append("  PaymentDescription: ").Append(PaymentDescription).Append("\n");
            sb.Append("  RefundTransactions: ").Append(RefundTransactions).Append("\n");
            sb.Append("  TotalRefundAmount: ").Append(TotalRefundAmount).Append("\n");
            sb.Append("  RemainingAmount: ").Append(RemainingAmount).Append("\n");
            sb.Append("  ChargebackReason: ").Append(ChargebackReason).Append("\n");
            sb.Append("  ChargebackReasonCode: ").Append(ChargebackReasonCode).Append("\n");
            sb.Append("  ChargebackDateTime: ").Append(ChargebackDateTime).Append("\n");
            sb.Append("  SubTotalAmount: ").Append(SubTotalAmount).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
