/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PaymentLinkResponseCustomersInnerAccountsInner
    /// </summary>
    [DataContract(Name = "PaymentLinkResponse_customers_inner_accounts_inner")]
    public partial class PaymentLinkResponseCustomersInnerAccountsInner : IValidatableObject
    {
        /// <summary>
        /// Defines ChannelType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ChannelTypeEnum
        {
            /// <summary>
            /// Enum ACH for value: ACH
            /// </summary>
            [EnumMember(Value = "ACH")]
            ACH = 1,

            /// <summary>
            /// Enum CreditCard for value: CreditCard
            /// </summary>
            [EnumMember(Value = "CreditCard")]
            CreditCard = 2,

            /// <summary>
            /// Enum DebitCard for value: DebitCard
            /// </summary>
            [EnumMember(Value = "DebitCard")]
            DebitCard = 3,

            /// <summary>
            /// Enum RTP for value: RTP
            /// </summary>
            [EnumMember(Value = "RTP")]
            RTP = 4
        }


        /// <summary>
        /// Gets or Sets ChannelType
        /// </summary>
        [DataMember(Name = "channelType", EmitDefaultValue = false)]
        public ChannelTypeEnum? ChannelType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentLinkResponseCustomersInnerAccountsInner" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="channelType">channelType.</param>
        /// <param name="cardNumber">cardNumber.</param>
        /// <param name="cardType">cardType.</param>
        /// <param name="accountToken">accountToken.</param>
        /// <param name="accountNumber">accountNumber.</param>
        /// <param name="bankName">bankName.</param>
        /// <param name="isCheckingAccount">isCheckingAccount.</param>
        /// <param name="isExpired">isExpired.</param>
        /// <param name="createdOn">createdOn.</param>
        /// <param name="createdBy">createdBy.</param>
        /// <param name="modifiedOn">modifiedOn.</param>
        /// <param name="modifiedBy">modifiedBy.</param>
        public PaymentLinkResponseCustomersInnerAccountsInner(string id = default(string), ChannelTypeEnum? channelType = default(ChannelTypeEnum?), string cardNumber = default(string), string cardType = default(string), string accountToken = default(string), string accountNumber = default(string), string bankName = default(string), bool isCheckingAccount = default(bool), bool isExpired = default(bool), string createdOn = default(string), string createdBy = default(string), string modifiedOn = default(string), string modifiedBy = default(string))
        {
            this.Id = id;
            this.ChannelType = channelType;
            this.CardNumber = cardNumber;
            this.CardType = cardType;
            this.AccountToken = accountToken;
            this.AccountNumber = accountNumber;
            this.BankName = bankName;
            this.IsCheckingAccount = isCheckingAccount;
            this.IsExpired = isExpired;
            this.CreatedOn = createdOn;
            this.CreatedBy = createdBy;
            this.ModifiedOn = modifiedOn;
            this.ModifiedBy = modifiedBy;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets CardNumber
        /// </summary>
        [DataMember(Name = "cardNumber", EmitDefaultValue = false)]
        public string CardNumber { get; set; }

        /// <summary>
        /// Gets or Sets CardType
        /// </summary>
        [DataMember(Name = "cardType", EmitDefaultValue = false)]
        public string CardType { get; set; }

        /// <summary>
        /// Gets or Sets AccountToken
        /// </summary>
        [DataMember(Name = "accountToken", EmitDefaultValue = false)]
        public string AccountToken { get; set; }

        /// <summary>
        /// Gets or Sets AccountNumber
        /// </summary>
        [DataMember(Name = "accountNumber", EmitDefaultValue = false)]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Gets or Sets BankName
        /// </summary>
        [DataMember(Name = "bankName", EmitDefaultValue = false)]
        public string BankName { get; set; }

        /// <summary>
        /// Gets or Sets IsCheckingAccount
        /// </summary>
        [DataMember(Name = "isCheckingAccount", EmitDefaultValue = true)]
        public bool IsCheckingAccount { get; set; }

        /// <summary>
        /// Gets or Sets IsExpired
        /// </summary>
        [DataMember(Name = "isExpired", EmitDefaultValue = true)]
        public bool IsExpired { get; set; }

        /// <summary>
        /// Gets or Sets CreatedOn
        /// </summary>
        [DataMember(Name = "createdOn", EmitDefaultValue = false)]
        public string CreatedOn { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name = "createdBy", EmitDefaultValue = false)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedOn
        /// </summary>
        [DataMember(Name = "modifiedOn", EmitDefaultValue = false)]
        public string ModifiedOn { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedBy
        /// </summary>
        [DataMember(Name = "modifiedBy", EmitDefaultValue = false)]
        public string ModifiedBy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentLinkResponseCustomersInnerAccountsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ChannelType: ").Append(ChannelType).Append("\n");
            sb.Append("  CardNumber: ").Append(CardNumber).Append("\n");
            sb.Append("  CardType: ").Append(CardType).Append("\n");
            sb.Append("  AccountToken: ").Append(AccountToken).Append("\n");
            sb.Append("  AccountNumber: ").Append(AccountNumber).Append("\n");
            sb.Append("  BankName: ").Append(BankName).Append("\n");
            sb.Append("  IsCheckingAccount: ").Append(IsCheckingAccount).Append("\n");
            sb.Append("  IsExpired: ").Append(IsExpired).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  ModifiedOn: ").Append(ModifiedOn).Append("\n");
            sb.Append("  ModifiedBy: ").Append(ModifiedBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
