/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PaymentLinkResponseCallbackParameters
    /// </summary>
    [DataContract(Name = "PaymentLinkResponse_callbackParameters")]
    public partial class PaymentLinkResponseCallbackParameters : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentLinkResponseCallbackParameters" /> class.
        /// </summary>
        /// <param name="callbackSuccessUrl">callbackSuccessUrl.</param>
        /// <param name="callbackFailureUrl">callbackFailureUrl.</param>
        /// <param name="accessKey">accessKey.</param>
        /// <param name="secretKey">secretKey.</param>
        /// <param name="referenceNo">referenceNo.</param>
        /// <param name="referenceType">referenceType.</param>
        /// <param name="transactionId">transactionId.</param>
        /// <param name="callbackApiUrl">callbackApiUrl.</param>
        /// <param name="callbackMessage">callbackMessage.</param>
        /// <param name="redirectionTime">redirectionTime.</param>
        public PaymentLinkResponseCallbackParameters(string callbackSuccessUrl = default(string), string callbackFailureUrl = default(string), string accessKey = default(string), string secretKey = default(string), string referenceNo = default(string), string referenceType = default(string), string transactionId = default(string), string callbackApiUrl = default(string), string callbackMessage = default(string), float redirectionTime = default(float))
        {
            this.CallbackSuccessUrl = callbackSuccessUrl;
            this.CallbackFailureUrl = callbackFailureUrl;
            this.AccessKey = accessKey;
            this.SecretKey = secretKey;
            this.ReferenceNo = referenceNo;
            this.ReferenceType = referenceType;
            this.TransactionId = transactionId;
            this.CallbackApiUrl = callbackApiUrl;
            this.CallbackMessage = callbackMessage;
            this.RedirectionTime = redirectionTime;
        }

        /// <summary>
        /// Gets or Sets CallbackSuccessUrl
        /// </summary>
        [DataMember(Name = "callbackSuccessUrl", EmitDefaultValue = false)]
        public string CallbackSuccessUrl { get; set; }

        /// <summary>
        /// Gets or Sets CallbackFailureUrl
        /// </summary>
        [DataMember(Name = "callbackFailureUrl", EmitDefaultValue = false)]
        public string CallbackFailureUrl { get; set; }

        /// <summary>
        /// Gets or Sets AccessKey
        /// </summary>
        [DataMember(Name = "accessKey", EmitDefaultValue = false)]
        public string AccessKey { get; set; }

        /// <summary>
        /// Gets or Sets SecretKey
        /// </summary>
        [DataMember(Name = "secretKey", EmitDefaultValue = false)]
        public string SecretKey { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceNo
        /// </summary>
        [DataMember(Name = "referenceNo", EmitDefaultValue = false)]
        public string ReferenceNo { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceType
        /// </summary>
        [DataMember(Name = "referenceType", EmitDefaultValue = false)]
        public string ReferenceType { get; set; }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transactionId", EmitDefaultValue = false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets CallbackApiUrl
        /// </summary>
        [DataMember(Name = "callbackApiUrl", EmitDefaultValue = false)]
        public string CallbackApiUrl { get; set; }

        /// <summary>
        /// Gets or Sets CallbackMessage
        /// </summary>
        [DataMember(Name = "callbackMessage", EmitDefaultValue = false)]
        public string CallbackMessage { get; set; }

        /// <summary>
        /// Gets or Sets RedirectionTime
        /// </summary>
        [DataMember(Name = "redirectionTime", EmitDefaultValue = false)]
        public float RedirectionTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentLinkResponseCallbackParameters {\n");
            sb.Append("  CallbackSuccessUrl: ").Append(CallbackSuccessUrl).Append("\n");
            sb.Append("  CallbackFailureUrl: ").Append(CallbackFailureUrl).Append("\n");
            sb.Append("  AccessKey: ").Append(AccessKey).Append("\n");
            sb.Append("  SecretKey: ").Append(SecretKey).Append("\n");
            sb.Append("  ReferenceNo: ").Append(ReferenceNo).Append("\n");
            sb.Append("  ReferenceType: ").Append(ReferenceType).Append("\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  CallbackApiUrl: ").Append(CallbackApiUrl).Append("\n");
            sb.Append("  CallbackMessage: ").Append(CallbackMessage).Append("\n");
            sb.Append("  RedirectionTime: ").Append(RedirectionTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
