/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PFEndorsementResponseItem
    /// </summary>
    [DataContract(Name = "PFEndorsementResponse_item")]
    public partial class PFEndorsementResponseItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PFEndorsementResponseItem" /> class.
        /// </summary>
        /// <param name="saveStatus">saveStatus.</param>
        /// <param name="quote">quote.</param>
        /// <param name="paymentIntent">paymentIntent.</param>
        public PFEndorsementResponseItem(string saveStatus = default(string), PFEndorsementResponseItemQuote quote = default(PFEndorsementResponseItemQuote), PFEndorsementResponseItemPaymentIntent paymentIntent = default(PFEndorsementResponseItemPaymentIntent))
        {
            this.SaveStatus = saveStatus;
            this.Quote = quote;
            this.PaymentIntent = paymentIntent;
        }

        /// <summary>
        /// Gets or Sets SaveStatus
        /// </summary>
        [DataMember(Name = "saveStatus", EmitDefaultValue = false)]
        public string SaveStatus { get; set; }

        /// <summary>
        /// Gets or Sets Quote
        /// </summary>
        [DataMember(Name = "quote", EmitDefaultValue = false)]
        public PFEndorsementResponseItemQuote Quote { get; set; }

        /// <summary>
        /// Gets or Sets PaymentIntent
        /// </summary>
        [DataMember(Name = "paymentIntent", EmitDefaultValue = false)]
        public PFEndorsementResponseItemPaymentIntent PaymentIntent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PFEndorsementResponseItem {\n");
            sb.Append("  SaveStatus: ").Append(SaveStatus).Append("\n");
            sb.Append("  Quote: ").Append(Quote).Append("\n");
            sb.Append("  PaymentIntent: ").Append(PaymentIntent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
