/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner
    /// </summary>
    [DataContract(Name = "PFEndorsementRequest_quote_policies_inner_totalPayFunding_inner")]
    public partial class PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner" /> class.
        /// </summary>
        /// <param name="payTo">payTo.</param>
        /// <param name="paymentMethod">paymentMethod.</param>
        /// <param name="fundingType">fundingType.</param>
        /// <param name="bankRoutingNumber">bankRoutingNumber.</param>
        /// <param name="bankAcctNumber">bankAcctNumber.</param>
        /// <param name="isCheckingAccount">isCheckingAccount.</param>
        /// <param name="amount">amount.</param>
        /// <param name="fundingDate">fundingDate.</param>
        public PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner(string payTo = default(string), string paymentMethod = default(string), string fundingType = default(string), string bankRoutingNumber = default(string), string bankAcctNumber = default(string), bool isCheckingAccount = default(bool), decimal amount = default(decimal), string fundingDate = default(string))
        {
            this.PayTo = payTo;
            this.PaymentMethod = paymentMethod;
            this.FundingType = fundingType;
            this.BankRoutingNumber = bankRoutingNumber;
            this.BankAcctNumber = bankAcctNumber;
            this.IsCheckingAccount = isCheckingAccount;
            this.Amount = amount;
            this.FundingDate = fundingDate;
        }

        /// <summary>
        /// Gets or Sets PayTo
        /// </summary>
        [DataMember(Name = "PayTo", EmitDefaultValue = false)]
        public string PayTo { get; set; }

        /// <summary>
        /// Gets or Sets PaymentMethod
        /// </summary>
        [DataMember(Name = "PaymentMethod", EmitDefaultValue = false)]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// Gets or Sets FundingType
        /// </summary>
        [DataMember(Name = "FundingType", EmitDefaultValue = false)]
        public string FundingType { get; set; }

        /// <summary>
        /// Gets or Sets BankRoutingNumber
        /// </summary>
        [DataMember(Name = "BankRoutingNumber", EmitDefaultValue = false)]
        public string BankRoutingNumber { get; set; }

        /// <summary>
        /// Gets or Sets BankAcctNumber
        /// </summary>
        [DataMember(Name = "BankAcctNumber", EmitDefaultValue = false)]
        public string BankAcctNumber { get; set; }

        /// <summary>
        /// Gets or Sets IsCheckingAccount
        /// </summary>
        [DataMember(Name = "IsCheckingAccount", EmitDefaultValue = true)]
        public bool IsCheckingAccount { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "Amount", EmitDefaultValue = false)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or Sets FundingDate
        /// </summary>
        [DataMember(Name = "FundingDate", EmitDefaultValue = false)]
        public string FundingDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner {\n");
            sb.Append("  PayTo: ").Append(PayTo).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("  FundingType: ").Append(FundingType).Append("\n");
            sb.Append("  BankRoutingNumber: ").Append(BankRoutingNumber).Append("\n");
            sb.Append("  BankAcctNumber: ").Append(BankAcctNumber).Append("\n");
            sb.Append("  IsCheckingAccount: ").Append(IsCheckingAccount).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  FundingDate: ").Append(FundingDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
