/*
 * Secure API
 *
 * Secure API's
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PFEndorsementRequestQuoteAgent
    /// </summary>
    [DataContract(Name = "PFEndorsementRequest_quote_Agent")]
    public partial class PFEndorsementRequestQuoteAgent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PFEndorsementRequestQuoteAgent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PFEndorsementRequestQuoteAgent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PFEndorsementRequestQuoteAgent" /> class.
        /// </summary>
        /// <param name="uniqueID">This denotes the Unique ID..</param>
        /// <param name="email">This denotes the email of the agent. (required).</param>
        /// <param name="address">address (required).</param>
        public PFEndorsementRequestQuoteAgent(string uniqueID = default(string), string email = default(string), PFEndorsementRequestQuoteAgentAddress address = default(PFEndorsementRequestQuoteAgentAddress))
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for PFEndorsementRequestQuoteAgent and cannot be null");
            }
            this.Email = email;
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new ArgumentNullException("address is a required property for PFEndorsementRequestQuoteAgent and cannot be null");
            }
            this.Address = address;
            this.UniqueID = uniqueID;
        }

        /// <summary>
        /// This denotes the Unique ID.
        /// </summary>
        /// <value>This denotes the Unique ID.</value>
        [DataMember(Name = "UniqueID", EmitDefaultValue = false)]
        public string UniqueID { get; set; }

        /// <summary>
        /// This denotes the email of the agent.
        /// </summary>
        /// <value>This denotes the email of the agent.</value>
        [DataMember(Name = "Email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name = "Address", IsRequired = true, EmitDefaultValue = true)]
        public PFEndorsementRequestQuoteAgentAddress Address { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PFEndorsementRequestQuoteAgent {\n");
            sb.Append("  UniqueID: ").Append(UniqueID).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
