/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PFLiteGenerateQuoteResponseItemESignResult
    /// </summary>
    [DataContract(Name = "PFLiteGenerateQuoteResponse_item_eSignResult")]
    public partial class PFLiteGenerateQuoteResponseItemESignResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PFLiteGenerateQuoteResponseItemESignResult" /> class.
        /// </summary>
        /// <param name="processed">processed.</param>
        /// <param name="message">message.</param>
        /// <param name="batchId">batchId.</param>
        /// <param name="agentUrl">agentUrl.</param>
        /// <param name="insuredUrl">insuredUrl.</param>
        /// <param name="eSignOption">eSignOption.</param>
        public PFLiteGenerateQuoteResponseItemESignResult(bool processed = default(bool), string message = default(string), string batchId = default(string), string agentUrl = default(string), string insuredUrl = default(string), float eSignOption = default(float))
        {
            this.Processed = processed;
            this.Message = message;
            this.BatchId = batchId;
            this.AgentUrl = agentUrl;
            this.InsuredUrl = insuredUrl;
            this.ESignOption = eSignOption;
        }

        /// <summary>
        /// Gets or Sets Processed
        /// </summary>
        [DataMember(Name = "processed", EmitDefaultValue = true)]
        public bool Processed { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets BatchId
        /// </summary>
        [DataMember(Name = "batchId", EmitDefaultValue = false)]
        public string BatchId { get; set; }

        /// <summary>
        /// Gets or Sets AgentUrl
        /// </summary>
        [DataMember(Name = "agentUrl", EmitDefaultValue = false)]
        public string AgentUrl { get; set; }

        /// <summary>
        /// Gets or Sets InsuredUrl
        /// </summary>
        [DataMember(Name = "insuredUrl", EmitDefaultValue = false)]
        public string InsuredUrl { get; set; }

        /// <summary>
        /// Gets or Sets ESignOption
        /// </summary>
        [DataMember(Name = "eSignOption", EmitDefaultValue = false)]
        public float ESignOption { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PFLiteGenerateQuoteResponseItemESignResult {\n");
            sb.Append("  Processed: ").Append(Processed).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  BatchId: ").Append(BatchId).Append("\n");
            sb.Append("  AgentUrl: ").Append(AgentUrl).Append("\n");
            sb.Append("  InsuredUrl: ").Append(InsuredUrl).Append("\n");
            sb.Append("  ESignOption: ").Append(ESignOption).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
