/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PFLiteSecureQuoteRequestProgram
    /// </summary>
    [DataContract(Name = "PFLiteSecureQuoteRequest_program")]
    public partial class PFLiteSecureQuoteRequestProgram : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PFLiteSecureQuoteRequestProgram" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PFLiteSecureQuoteRequestProgram() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PFLiteSecureQuoteRequestProgram" /> class.
        /// </summary>
        /// <param name="programId">programId.</param>
        /// <param name="loanType">loanType (required).</param>
        public PFLiteSecureQuoteRequestProgram(string programId = default(string), string loanType = default(string))
        {
            // to ensure "loanType" is required (not null)
            if (loanType == null)
            {
                throw new ArgumentNullException("loanType is a required property for PFLiteSecureQuoteRequestProgram and cannot be null");
            }
            this.LoanType = loanType;
            this.ProgramId = programId;
        }

        /// <summary>
        /// Gets or Sets ProgramId
        /// </summary>
        [DataMember(Name = "programId", EmitDefaultValue = false)]
        public string ProgramId { get; set; }

        /// <summary>
        /// Gets or Sets LoanType
        /// </summary>
        [DataMember(Name = "loanType", IsRequired = true, EmitDefaultValue = true)]
        public string LoanType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PFLiteSecureQuoteRequestProgram {\n");
            sb.Append("  ProgramId: ").Append(ProgramId).Append("\n");
            sb.Append("  LoanType: ").Append(LoanType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
