/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PFQuoteEsignRequest
    /// </summary>
    [DataContract(Name = "PFQuoteEsignRequest")]
    public partial class PFQuoteEsignRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PFQuoteEsignRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PFQuoteEsignRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PFQuoteEsignRequest" /> class.
        /// </summary>
        /// <param name="merchantToken">This denotes the merchant token..</param>
        /// <param name="quoteKey">This denotes the quoteKey. (required).</param>
        /// <param name="insuredName">This denotes the name of the insured. (required).</param>
        /// <param name="ipAddress">This denotes the IP address of the client..</param>
        /// <param name="macAddress">This denotes the MAC address of the client..</param>
        /// <param name="captchaToken">This denotes the captchaToken..</param>
        /// <param name="actionName">This denotes the action name..</param>
        public PFQuoteEsignRequest(string merchantToken = default(string), string quoteKey = default(string), string insuredName = default(string), string ipAddress = default(string), string macAddress = default(string), string captchaToken = default(string), string actionName = default(string))
        {
            // to ensure "quoteKey" is required (not null)
            if (quoteKey == null)
            {
                throw new ArgumentNullException("quoteKey is a required property for PFQuoteEsignRequest and cannot be null");
            }
            this.QuoteKey = quoteKey;
            // to ensure "insuredName" is required (not null)
            if (insuredName == null)
            {
                throw new ArgumentNullException("insuredName is a required property for PFQuoteEsignRequest and cannot be null");
            }
            this.InsuredName = insuredName;
            this.MerchantToken = merchantToken;
            this.IpAddress = ipAddress;
            this.MacAddress = macAddress;
            this.CaptchaToken = captchaToken;
            this.ActionName = actionName;
        }

        /// <summary>
        /// This denotes the merchant token.
        /// </summary>
        /// <value>This denotes the merchant token.</value>
        [DataMember(Name = "merchantToken", EmitDefaultValue = false)]
        public string MerchantToken { get; set; }

        /// <summary>
        /// This denotes the quoteKey.
        /// </summary>
        /// <value>This denotes the quoteKey.</value>
        [DataMember(Name = "quoteKey", IsRequired = true, EmitDefaultValue = true)]
        public string QuoteKey { get; set; }

        /// <summary>
        /// This denotes the name of the insured.
        /// </summary>
        /// <value>This denotes the name of the insured.</value>
        [DataMember(Name = "insuredName", IsRequired = true, EmitDefaultValue = true)]
        public string InsuredName { get; set; }

        /// <summary>
        /// This denotes the IP address of the client.
        /// </summary>
        /// <value>This denotes the IP address of the client.</value>
        [DataMember(Name = "ipAddress", EmitDefaultValue = false)]
        public string IpAddress { get; set; }

        /// <summary>
        /// This denotes the MAC address of the client.
        /// </summary>
        /// <value>This denotes the MAC address of the client.</value>
        [DataMember(Name = "macAddress", EmitDefaultValue = false)]
        public string MacAddress { get; set; }

        /// <summary>
        /// This denotes the captchaToken.
        /// </summary>
        /// <value>This denotes the captchaToken.</value>
        [DataMember(Name = "captchaToken", EmitDefaultValue = false)]
        public string CaptchaToken { get; set; }

        /// <summary>
        /// This denotes the action name.
        /// </summary>
        /// <value>This denotes the action name.</value>
        [DataMember(Name = "actionName", EmitDefaultValue = false)]
        public string ActionName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PFQuoteEsignRequest {\n");
            sb.Append("  MerchantToken: ").Append(MerchantToken).Append("\n");
            sb.Append("  QuoteKey: ").Append(QuoteKey).Append("\n");
            sb.Append("  InsuredName: ").Append(InsuredName).Append("\n");
            sb.Append("  IpAddress: ").Append(IpAddress).Append("\n");
            sb.Append("  MacAddress: ").Append(MacAddress).Append("\n");
            sb.Append("  CaptchaToken: ").Append(CaptchaToken).Append("\n");
            sb.Append("  ActionName: ").Append(ActionName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
