/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SecureUpdatePaymentLinkRequestSettings
    /// </summary>
    [DataContract(Name = "SecureUpdatePaymentLinkRequest_settings")]
    public partial class SecureUpdatePaymentLinkRequestSettings : IValidatableObject
    {
        /// <summary>
        /// Defines AdditionalDetailsPreference
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AdditionalDetailsPreferenceEnum
        {
            /// <summary>
            /// Enum None for value: None
            /// </summary>
            [EnumMember(Value = "None")]
            None = 1,

            /// <summary>
            /// Enum AskShopper for value: AskShopper
            /// </summary>
            [EnumMember(Value = "AskShopper")]
            AskShopper = 2,

            /// <summary>
            /// Enum ManualEnter for value: ManualEnter
            /// </summary>
            [EnumMember(Value = "ManualEnter")]
            ManualEnter = 3,

            /// <summary>
            /// Enum NoAdditionalDetails for value: NoAdditionalDetails
            /// </summary>
            [EnumMember(Value = "NoAdditionalDetails")]
            NoAdditionalDetails = 4,

            /// <summary>
            /// Enum ManualEnterEditNotAllowed for value: ManualEnterEditNotAllowed
            /// </summary>
            [EnumMember(Value = "ManualEnterEditNotAllowed")]
            ManualEnterEditNotAllowed = 5
        }


        /// <summary>
        /// Gets or Sets AdditionalDetailsPreference
        /// </summary>
        [DataMember(Name = "additionalDetailsPreference", EmitDefaultValue = false)]
        public AdditionalDetailsPreferenceEnum? AdditionalDetailsPreference { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SecureUpdatePaymentLinkRequestSettings" /> class.
        /// </summary>
        /// <param name="selectedCustomerFields">selectedCustomerFields.</param>
        /// <param name="additionalDetailsPreference">additionalDetailsPreference.</param>
        /// <param name="displaySummary">displaySummary.</param>
        /// <param name="acceptCustomerInfo">acceptCustomerInfo.</param>
        /// <param name="removeHeader">removeHeader.</param>
        /// <param name="acceptCard">acceptCard.</param>
        /// <param name="acceptBankAccount">acceptBankAccount.</param>
        /// <param name="saveCustomer">saveCustomer.</param>
        /// <param name="saveCustomerAccount">saveCustomerAccount.</param>
        /// <param name="intent">intent.</param>
        public SecureUpdatePaymentLinkRequestSettings(string selectedCustomerFields = default(string), AdditionalDetailsPreferenceEnum? additionalDetailsPreference = default(AdditionalDetailsPreferenceEnum?), bool displaySummary = default(bool), bool acceptCustomerInfo = default(bool), bool removeHeader = default(bool), bool acceptCard = default(bool), bool acceptBankAccount = default(bool), bool saveCustomer = default(bool), bool saveCustomerAccount = default(bool), SecureUpdatePaymentLinkRequestSettingsIntent intent = default(SecureUpdatePaymentLinkRequestSettingsIntent))
        {
            this.SelectedCustomerFields = selectedCustomerFields;
            this.AdditionalDetailsPreference = additionalDetailsPreference;
            this.DisplaySummary = displaySummary;
            this.AcceptCustomerInfo = acceptCustomerInfo;
            this.RemoveHeader = removeHeader;
            this.AcceptCard = acceptCard;
            this.AcceptBankAccount = acceptBankAccount;
            this.SaveCustomer = saveCustomer;
            this.SaveCustomerAccount = saveCustomerAccount;
            this.Intent = intent;
        }

        /// <summary>
        /// Gets or Sets SelectedCustomerFields
        /// </summary>
        [DataMember(Name = "selectedCustomerFields", EmitDefaultValue = false)]
        public string SelectedCustomerFields { get; set; }

        /// <summary>
        /// Gets or Sets DisplaySummary
        /// </summary>
        [DataMember(Name = "displaySummary", EmitDefaultValue = true)]
        public bool DisplaySummary { get; set; }

        /// <summary>
        /// Gets or Sets AcceptCustomerInfo
        /// </summary>
        [DataMember(Name = "acceptCustomerInfo", EmitDefaultValue = true)]
        public bool AcceptCustomerInfo { get; set; }

        /// <summary>
        /// Gets or Sets RemoveHeader
        /// </summary>
        [DataMember(Name = "removeHeader", EmitDefaultValue = true)]
        public bool RemoveHeader { get; set; }

        /// <summary>
        /// Gets or Sets AcceptCard
        /// </summary>
        [DataMember(Name = "acceptCard", EmitDefaultValue = true)]
        public bool AcceptCard { get; set; }

        /// <summary>
        /// Gets or Sets AcceptBankAccount
        /// </summary>
        [DataMember(Name = "acceptBankAccount", EmitDefaultValue = true)]
        public bool AcceptBankAccount { get; set; }

        /// <summary>
        /// Gets or Sets SaveCustomer
        /// </summary>
        [DataMember(Name = "saveCustomer", EmitDefaultValue = true)]
        public bool SaveCustomer { get; set; }

        /// <summary>
        /// Gets or Sets SaveCustomerAccount
        /// </summary>
        [DataMember(Name = "saveCustomerAccount", EmitDefaultValue = true)]
        public bool SaveCustomerAccount { get; set; }

        /// <summary>
        /// Gets or Sets Intent
        /// </summary>
        [DataMember(Name = "intent", EmitDefaultValue = false)]
        public SecureUpdatePaymentLinkRequestSettingsIntent Intent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SecureUpdatePaymentLinkRequestSettings {\n");
            sb.Append("  SelectedCustomerFields: ").Append(SelectedCustomerFields).Append("\n");
            sb.Append("  AdditionalDetailsPreference: ").Append(AdditionalDetailsPreference).Append("\n");
            sb.Append("  DisplaySummary: ").Append(DisplaySummary).Append("\n");
            sb.Append("  AcceptCustomerInfo: ").Append(AcceptCustomerInfo).Append("\n");
            sb.Append("  RemoveHeader: ").Append(RemoveHeader).Append("\n");
            sb.Append("  AcceptCard: ").Append(AcceptCard).Append("\n");
            sb.Append("  AcceptBankAccount: ").Append(AcceptBankAccount).Append("\n");
            sb.Append("  SaveCustomer: ").Append(SaveCustomer).Append("\n");
            sb.Append("  SaveCustomerAccount: ").Append(SaveCustomerAccount).Append("\n");
            sb.Append("  Intent: ").Append(Intent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
