/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SecureTokenLinkByIdResponse
    /// </summary>
    [DataContract(Name = "SecureTokenLinkByIdResponse")]
    public partial class SecureTokenLinkByIdResponse : IValidatableObject
    {
        /// <summary>
        /// Defines TokenLinkStatus
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TokenLinkStatusEnum
        {
            /// <summary>
            /// Enum NA for value: NA
            /// </summary>
            [EnumMember(Value = "NA")]
            NA = 1,

            /// <summary>
            /// Enum Created for value: Created
            /// </summary>
            [EnumMember(Value = "Created")]
            Created = 2,

            /// <summary>
            /// Enum Completed for value: Completed
            /// </summary>
            [EnumMember(Value = "Completed")]
            Completed = 3,

            /// <summary>
            /// Enum Expired for value: Expired
            /// </summary>
            [EnumMember(Value = "Expired")]
            Expired = 4,

            /// <summary>
            /// Enum Invalidated for value: Invalidated
            /// </summary>
            [EnumMember(Value = "Invalidated")]
            Invalidated = 5,

            /// <summary>
            /// Enum Failed for value: Failed
            /// </summary>
            [EnumMember(Value = "Failed")]
            Failed = 6
        }


        /// <summary>
        /// Gets or Sets TokenLinkStatus
        /// </summary>
        [DataMember(Name = "tokenLinkStatus", EmitDefaultValue = false)]
        public TokenLinkStatusEnum? TokenLinkStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SecureTokenLinkByIdResponse" /> class.
        /// </summary>
        /// <param name="tokenLinkId">tokenLinkId.</param>
        /// <param name="title">title.</param>
        /// <param name="tokenLink">tokenLink.</param>
        /// <param name="expireOn">expireOn.</param>
        /// <param name="createdOn">createdOn.</param>
        /// <param name="modifiedOn">modifiedOn.</param>
        /// <param name="createdBy">createdBy.</param>
        /// <param name="modifiedBy">modifiedBy.</param>
        /// <param name="tokenLinkStatus">tokenLinkStatus.</param>
        /// <param name="accountToken">accountToken.</param>
        /// <param name="intent">intent.</param>
        /// <param name="customers">customers.</param>
        /// <param name="timeLine">timeLine.</param>
        public SecureTokenLinkByIdResponse(string tokenLinkId = default(string), string title = default(string), string tokenLink = default(string), string expireOn = default(string), string createdOn = default(string), string modifiedOn = default(string), string createdBy = default(string), string modifiedBy = default(string), TokenLinkStatusEnum? tokenLinkStatus = default(TokenLinkStatusEnum?), SecureTokenLinkByIdResponseAccountToken accountToken = default(SecureTokenLinkByIdResponseAccountToken), SecureTokenLinkByIdResponseIntent intent = default(SecureTokenLinkByIdResponseIntent), List<SecureTokenLinkResponseCustomersInner> customers = default(List<SecureTokenLinkResponseCustomersInner>), List<SecureTokenLinkByIdResponseTimeLineInner> timeLine = default(List<SecureTokenLinkByIdResponseTimeLineInner>))
        {
            this.TokenLinkId = tokenLinkId;
            this.Title = title;
            this.TokenLink = tokenLink;
            this.ExpireOn = expireOn;
            this.CreatedOn = createdOn;
            this.ModifiedOn = modifiedOn;
            this.CreatedBy = createdBy;
            this.ModifiedBy = modifiedBy;
            this.TokenLinkStatus = tokenLinkStatus;
            this.AccountToken = accountToken;
            this.Intent = intent;
            this.Customers = customers;
            this.TimeLine = timeLine;
        }

        /// <summary>
        /// Gets or Sets TokenLinkId
        /// </summary>
        [DataMember(Name = "tokenLinkId", EmitDefaultValue = false)]
        public string TokenLinkId { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets TokenLink
        /// </summary>
        [DataMember(Name = "tokenLink", EmitDefaultValue = false)]
        public string TokenLink { get; set; }

        /// <summary>
        /// Gets or Sets ExpireOn
        /// </summary>
        [DataMember(Name = "expireOn", EmitDefaultValue = false)]
        public string ExpireOn { get; set; }

        /// <summary>
        /// Gets or Sets CreatedOn
        /// </summary>
        [DataMember(Name = "createdOn", EmitDefaultValue = false)]
        public string CreatedOn { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedOn
        /// </summary>
        [DataMember(Name = "modifiedOn", EmitDefaultValue = false)]
        public string ModifiedOn { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name = "createdBy", EmitDefaultValue = false)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedBy
        /// </summary>
        [DataMember(Name = "modifiedBy", EmitDefaultValue = false)]
        public string ModifiedBy { get; set; }

        /// <summary>
        /// Gets or Sets AccountToken
        /// </summary>
        [DataMember(Name = "accountToken", EmitDefaultValue = false)]
        public SecureTokenLinkByIdResponseAccountToken AccountToken { get; set; }

        /// <summary>
        /// Gets or Sets Intent
        /// </summary>
        [DataMember(Name = "intent", EmitDefaultValue = false)]
        public SecureTokenLinkByIdResponseIntent Intent { get; set; }

        /// <summary>
        /// Gets or Sets Customers
        /// </summary>
        [DataMember(Name = "customers", EmitDefaultValue = false)]
        public List<SecureTokenLinkResponseCustomersInner> Customers { get; set; }

        /// <summary>
        /// Gets or Sets TimeLine
        /// </summary>
        [DataMember(Name = "timeLine", EmitDefaultValue = false)]
        public List<SecureTokenLinkByIdResponseTimeLineInner> TimeLine { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SecureTokenLinkByIdResponse {\n");
            sb.Append("  TokenLinkId: ").Append(TokenLinkId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  TokenLink: ").Append(TokenLink).Append("\n");
            sb.Append("  ExpireOn: ").Append(ExpireOn).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  ModifiedOn: ").Append(ModifiedOn).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  ModifiedBy: ").Append(ModifiedBy).Append("\n");
            sb.Append("  TokenLinkStatus: ").Append(TokenLinkStatus).Append("\n");
            sb.Append("  AccountToken: ").Append(AccountToken).Append("\n");
            sb.Append("  Intent: ").Append(Intent).Append("\n");
            sb.Append("  Customers: ").Append(Customers).Append("\n");
            sb.Append("  TimeLine: ").Append(TimeLine).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
