/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SecureTransactionRefundRequest
    /// </summary>
    [DataContract(Name = "SecureTransactionRefundRequest")]
    public partial class SecureTransactionRefundRequest : IValidatableObject
    {
        /// <summary>
        /// Defines RefundType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RefundTypeEnum
        {
            /// <summary>
            /// Enum NA for value: NA
            /// </summary>
            [EnumMember(Value = "NA")]
            NA = 1,

            /// <summary>
            /// Enum Total for value: Total
            /// </summary>
            [EnumMember(Value = "Total")]
            Total = 2,

            /// <summary>
            /// Enum Subtotal for value: Subtotal
            /// </summary>
            [EnumMember(Value = "Subtotal")]
            Subtotal = 3,

            /// <summary>
            /// Enum Remaining for value: Remaining
            /// </summary>
            [EnumMember(Value = "Remaining")]
            Remaining = 4,

            /// <summary>
            /// Enum Partial for value: Partial
            /// </summary>
            [EnumMember(Value = "Partial")]
            Partial = 5
        }


        /// <summary>
        /// Gets or Sets RefundType
        /// </summary>
        [DataMember(Name = "refundType", EmitDefaultValue = false)]
        public RefundTypeEnum? RefundType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SecureTransactionRefundRequest" /> class.
        /// </summary>
        /// <param name="invoiceNumber">invoiceNumber.</param>
        /// <param name="pONumber">pONumber.</param>
        /// <param name="refundAmount">refundAmount.</param>
        /// <param name="transactionId">transactionId.</param>
        /// <param name="remarks">remarks.</param>
        /// <param name="refundReason">refundReason.</param>
        /// <param name="refundDetail">refundDetail.</param>
        /// <param name="refundType">refundType.</param>
        /// <param name="splits">splits.</param>
        public SecureTransactionRefundRequest(string invoiceNumber = default(string), string pONumber = default(string), decimal refundAmount = default(decimal), string transactionId = default(string), string remarks = default(string), string refundReason = default(string), string refundDetail = default(string), RefundTypeEnum? refundType = default(RefundTypeEnum?), List<PaymentIntentResponseSplitsInner> splits = default(List<PaymentIntentResponseSplitsInner>))
        {
            this.InvoiceNumber = invoiceNumber;
            this.PONumber = pONumber;
            this.RefundAmount = refundAmount;
            this.TransactionId = transactionId;
            this.Remarks = remarks;
            this.RefundReason = refundReason;
            this.RefundDetail = refundDetail;
            this.RefundType = refundType;
            this.Splits = splits;
        }

        /// <summary>
        /// Gets or Sets InvoiceNumber
        /// </summary>
        [DataMember(Name = "invoiceNumber", EmitDefaultValue = false)]
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets PONumber
        /// </summary>
        [DataMember(Name = "pONumber", EmitDefaultValue = false)]
        public string PONumber { get; set; }

        /// <summary>
        /// Gets or Sets RefundAmount
        /// </summary>
        [DataMember(Name = "refundAmount", EmitDefaultValue = false)]
        public decimal RefundAmount { get; set; }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transactionId", EmitDefaultValue = false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets Remarks
        /// </summary>
        [DataMember(Name = "remarks", EmitDefaultValue = false)]
        public string Remarks { get; set; }

        /// <summary>
        /// Gets or Sets RefundReason
        /// </summary>
        [DataMember(Name = "refundReason", EmitDefaultValue = false)]
        public string RefundReason { get; set; }

        /// <summary>
        /// Gets or Sets RefundDetail
        /// </summary>
        [DataMember(Name = "refundDetail", EmitDefaultValue = false)]
        public string RefundDetail { get; set; }

        /// <summary>
        /// Gets or Sets Splits
        /// </summary>
        [DataMember(Name = "splits", EmitDefaultValue = false)]
        public List<PaymentIntentResponseSplitsInner> Splits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SecureTransactionRefundRequest {\n");
            sb.Append("  InvoiceNumber: ").Append(InvoiceNumber).Append("\n");
            sb.Append("  PONumber: ").Append(PONumber).Append("\n");
            sb.Append("  RefundAmount: ").Append(RefundAmount).Append("\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  Remarks: ").Append(Remarks).Append("\n");
            sb.Append("  RefundReason: ").Append(RefundReason).Append("\n");
            sb.Append("  RefundDetail: ").Append(RefundDetail).Append("\n");
            sb.Append("  RefundType: ").Append(RefundType).Append("\n");
            sb.Append("  Splits: ").Append(Splits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
