/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SecureVendorUpdateRequestDTORemittanceAddress
    /// </summary>
    [DataContract(Name = "SecureVendorUpdateRequestDTO_remittanceAddress")]
    public partial class SecureVendorUpdateRequestDTORemittanceAddress : IValidatableObject
    {
        /// <summary>
        /// Defines AddressType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AddressTypeEnum
        {
            /// <summary>
            /// Enum NA for value: NA
            /// </summary>
            [EnumMember(Value = "NA")]
            NA = 1,

            /// <summary>
            /// Enum Remittance for value: Remittance
            /// </summary>
            [EnumMember(Value = "Remittance")]
            Remittance = 2,

            /// <summary>
            /// Enum Correspondence for value: Correspondence
            /// </summary>
            [EnumMember(Value = "Correspondence")]
            Correspondence = 3,

            /// <summary>
            /// Enum Physical for value: Physical
            /// </summary>
            [EnumMember(Value = "Physical")]
            Physical = 4
        }


        /// <summary>
        /// Gets or Sets AddressType
        /// </summary>
        [DataMember(Name = "addressType", EmitDefaultValue = false)]
        public AddressTypeEnum? AddressType { get; set; }
        /// <summary>
        /// Defines AddressSource
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AddressSourceEnum
        {
            /// <summary>
            /// Enum NA for value: NA
            /// </summary>
            [EnumMember(Value = "NA")]
            NA = 1
        }


        /// <summary>
        /// Gets or Sets AddressSource
        /// </summary>
        [DataMember(Name = "addressSource", EmitDefaultValue = false)]
        public AddressSourceEnum? AddressSource { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SecureVendorUpdateRequestDTORemittanceAddress" /> class.
        /// </summary>
        /// <param name="attention">attention.</param>
        /// <param name="addressLine1">addressLine1.</param>
        /// <param name="addressLine2">addressLine2.</param>
        /// <param name="city">city.</param>
        /// <param name="state">state.</param>
        /// <param name="country">country.</param>
        /// <param name="postalCode">postalCode.</param>
        /// <param name="addressType">addressType.</param>
        /// <param name="addressSource">addressSource.</param>
        public SecureVendorUpdateRequestDTORemittanceAddress(string attention = default(string), string addressLine1 = default(string), string addressLine2 = default(string), string city = default(string), string state = default(string), string country = default(string), string postalCode = default(string), AddressTypeEnum? addressType = default(AddressTypeEnum?), AddressSourceEnum? addressSource = default(AddressSourceEnum?))
        {
            this.Attention = attention;
            this.AddressLine1 = addressLine1;
            this.AddressLine2 = addressLine2;
            this.City = city;
            this.State = state;
            this.Country = country;
            this.PostalCode = postalCode;
            this.AddressType = addressType;
            this.AddressSource = addressSource;
        }

        /// <summary>
        /// Gets or Sets Attention
        /// </summary>
        [DataMember(Name = "attention", EmitDefaultValue = false)]
        public string Attention { get; set; }

        /// <summary>
        /// Gets or Sets AddressLine1
        /// </summary>
        [DataMember(Name = "addressLine1", EmitDefaultValue = false)]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// Gets or Sets AddressLine2
        /// </summary>
        [DataMember(Name = "addressLine2", EmitDefaultValue = false)]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        [DataMember(Name = "city", EmitDefaultValue = false)]
        public string City { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets PostalCode
        /// </summary>
        [DataMember(Name = "postalCode", EmitDefaultValue = false)]
        public string PostalCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SecureVendorUpdateRequestDTORemittanceAddress {\n");
            sb.Append("  Attention: ").Append(Attention).Append("\n");
            sb.Append("  AddressLine1: ").Append(AddressLine1).Append("\n");
            sb.Append("  AddressLine2: ").Append(AddressLine2).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  AddressType: ").Append(AddressType).Append("\n");
            sb.Append("  AddressSource: ").Append(AddressSource).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
