/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TransactionPaymentResponseTransactionEntitySplitResponsesInner
    /// </summary>
    [DataContract(Name = "TransactionPaymentResponse_transactionEntitySplitResponses_inner")]
    public partial class TransactionPaymentResponseTransactionEntitySplitResponsesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionPaymentResponseTransactionEntitySplitResponsesInner" /> class.
        /// </summary>
        /// <param name="accountAlias">accountAlias.</param>
        /// <param name="amount">amount.</param>
        /// <param name="chargeIndicator">chargeIndicator.</param>
        public TransactionPaymentResponseTransactionEntitySplitResponsesInner(string accountAlias = default(string), float amount = default(float), bool chargeIndicator = default(bool))
        {
            this.AccountAlias = accountAlias;
            this.Amount = amount;
            this.ChargeIndicator = chargeIndicator;
        }

        /// <summary>
        /// Gets or Sets AccountAlias
        /// </summary>
        [DataMember(Name = "accountAlias", EmitDefaultValue = false)]
        public string AccountAlias { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", EmitDefaultValue = false)]
        public float Amount { get; set; }

        /// <summary>
        /// Gets or Sets ChargeIndicator
        /// </summary>
        [DataMember(Name = "chargeIndicator", EmitDefaultValue = true)]
        public bool ChargeIndicator { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionPaymentResponseTransactionEntitySplitResponsesInner {\n");
            sb.Append("  AccountAlias: ").Append(AccountAlias).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  ChargeIndicator: ").Append(ChargeIndicator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
