/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// VendorRequestDTOPhysicalAddress
    /// </summary>
    [DataContract(Name = "VendorRequestDTO_physicalAddress")]
    public partial class VendorRequestDTOPhysicalAddress : IValidatableObject
    {
        /// <summary>
        /// Defines AddressSource
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AddressSourceEnum
        {
            /// <summary>
            /// Enum NA for value: NA
            /// </summary>
            [EnumMember(Value = "NA")]
            NA = 1,

            /// <summary>
            /// Enum Manual for value: Manual
            /// </summary>
            [EnumMember(Value = "Manual")]
            Manual = 2,

            /// <summary>
            /// Enum SmartyLookup for value: Smarty_lookup
            /// </summary>
            [EnumMember(Value = "Smarty_lookup")]
            SmartyLookup = 3
        }


        /// <summary>
        /// Gets or Sets AddressSource
        /// </summary>
        [DataMember(Name = "addressSource", IsRequired = true, EmitDefaultValue = true)]
        public AddressSourceEnum AddressSource { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VendorRequestDTOPhysicalAddress" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VendorRequestDTOPhysicalAddress() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VendorRequestDTOPhysicalAddress" /> class.
        /// </summary>
        /// <param name="attention">attention (required).</param>
        /// <param name="addressLine1">addressLine1 (required).</param>
        /// <param name="addressLine2">addressLine2.</param>
        /// <param name="city">city (required).</param>
        /// <param name="state">state (required).</param>
        /// <param name="country">country (required).</param>
        /// <param name="postalCode">postalCode (required).</param>
        /// <param name="addressSource">addressSource (required).</param>
        public VendorRequestDTOPhysicalAddress(string attention = default(string), string addressLine1 = default(string), string addressLine2 = default(string), string city = default(string), string state = default(string), string country = default(string), string postalCode = default(string), AddressSourceEnum addressSource = default(AddressSourceEnum))
        {
            // to ensure "attention" is required (not null)
            if (attention == null)
            {
                throw new ArgumentNullException("attention is a required property for VendorRequestDTOPhysicalAddress and cannot be null");
            }
            this.Attention = attention;
            // to ensure "addressLine1" is required (not null)
            if (addressLine1 == null)
            {
                throw new ArgumentNullException("addressLine1 is a required property for VendorRequestDTOPhysicalAddress and cannot be null");
            }
            this.AddressLine1 = addressLine1;
            // to ensure "city" is required (not null)
            if (city == null)
            {
                throw new ArgumentNullException("city is a required property for VendorRequestDTOPhysicalAddress and cannot be null");
            }
            this.City = city;
            // to ensure "state" is required (not null)
            if (state == null)
            {
                throw new ArgumentNullException("state is a required property for VendorRequestDTOPhysicalAddress and cannot be null");
            }
            this.State = state;
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for VendorRequestDTOPhysicalAddress and cannot be null");
            }
            this.Country = country;
            // to ensure "postalCode" is required (not null)
            if (postalCode == null)
            {
                throw new ArgumentNullException("postalCode is a required property for VendorRequestDTOPhysicalAddress and cannot be null");
            }
            this.PostalCode = postalCode;
            this.AddressSource = addressSource;
            this.AddressLine2 = addressLine2;
        }

        /// <summary>
        /// Gets or Sets Attention
        /// </summary>
        [DataMember(Name = "attention", IsRequired = true, EmitDefaultValue = true)]
        public string Attention { get; set; }

        /// <summary>
        /// Gets or Sets AddressLine1
        /// </summary>
        [DataMember(Name = "addressLine1", IsRequired = true, EmitDefaultValue = true)]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// Gets or Sets AddressLine2
        /// </summary>
        [DataMember(Name = "addressLine2", EmitDefaultValue = false)]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        [DataMember(Name = "city", IsRequired = true, EmitDefaultValue = true)]
        public string City { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", IsRequired = true, EmitDefaultValue = true)]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets PostalCode
        /// </summary>
        [DataMember(Name = "postalCode", IsRequired = true, EmitDefaultValue = true)]
        public string PostalCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VendorRequestDTOPhysicalAddress {\n");
            sb.Append("  Attention: ").Append(Attention).Append("\n");
            sb.Append("  AddressLine1: ").Append(AddressLine1).Append("\n");
            sb.Append("  AddressLine2: ").Append(AddressLine2).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  AddressSource: ").Append(AddressSource).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
