/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Xunit.Abstractions;
// uncomment below to import models
using Org.OpenAPITools.Model;
using Newtonsoft.Json.Linq;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SecureEmbeddedPremiumFinanceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SecureEmbeddedPremiumFinanceApiTests(ITestOutputHelper output) : IDisposable
    {
        private SecureEmbeddedPremiumFinanceApi instance = new();
        private readonly ITestOutputHelper output = output;

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureEmbeddedPremiumFinanceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SecureEmbeddedPremiumFinanceApi
            //Assert.IsType<SecureEmbeddedPremiumFinanceApi>(instance);
        }

        /// <summary>
        /// Test SecureEpfMerchantsQuotesPolicyPut
        /// </summary>
        [Fact]
        public void SecureEpfMerchantsQuotesPolicyPutTest()
        {
            Configuration config = new()
            {
                BasePath = "https://api.uat.anddone.com"
            };

            var apiInstance = new SecureEmbeddedPremiumFinanceApi(config);
            using StreamReader r = new("C:\\Work\\AndDone_SDKs\\anddone-csharp-sdk-openapi-codegen\\config.json");
            dynamic jsonConfig = JObject.Parse(r.ReadToEnd());
            
            string xApiKey = jsonConfig.xApiKey;
            string xAppKey = jsonConfig.xAppKey;
            float xVersion = jsonConfig.xVersion;
            string origin = jsonConfig.origin;
            PFPolicyUpdateRequestDTO request = new(
                quoteKey: 29694517,
                premium: 9000,
                category: "FIRE",
                newPolicyNumber: "1256"
            );
            try
            {
                // This API will do return a quote for an existing policy or new policy for an existing account
                ApiResponse<PFPolicyUpdateResponse> response = apiInstance.SecureEpfMerchantsQuotesPolicyPutWithHttpInfo(xApiKey, xAppKey, xVersion, origin, request);
                // output.WriteLine(response.Data.Title);
                output.WriteLine("Status Code: " + response.StatusCode);
                output.WriteLine("Response Body: " + response.RawContent);
            }

            catch (ApiException e)
            {
                output.WriteLine("Exception when calling SecureEmbeddedPremiumFinanceApi.SecureEpfMerchantsQuotesPolicyPut: " + e.Message);
                output.WriteLine("Status Code: " + e.ErrorCode);
                output.WriteLine(e.StackTrace);
            }
            //Assert.IsType<PFPolicyUpdateResponse>(response);
        }

        /// <summary>
        /// Test SecureEpfQuotesBookingPut
        /// </summary>
        [Fact]
        public void SecureEpfQuotesBookingPutTest()
        {
            Configuration config = new()
            {
                BasePath = "https://api.uat.anddone.com"
            };

            var apiInstance = new SecureEmbeddedPremiumFinanceApi(config);
            using StreamReader r = new("C:\\Work\\AndDone_SDKs\\anddone-csharp-sdk-openapi-codegen\\config.json");
            dynamic jsonConfig = JObject.Parse(r.ReadToEnd());
            
            string xApiKey = jsonConfig.xApiKey;
            string xAppKey = jsonConfig.xAppKey;
            float xVersion = jsonConfig.xVersion;
            string origin = jsonConfig.origin;
            PFQuoteBookingRequest request = new(
                quoteKey: 29694517
            );
            try
            {
                // This API will do return a quote for an existing policy or new policy for an existing account
                ApiResponse<PFUpdatePFAResponse> response = apiInstance.SecureEpfQuotesBookingPutWithHttpInfo(xApiKey, xAppKey, xVersion, origin, request);
                // output.WriteLine(response.Data.Title);
                output.WriteLine("Status Code: " + response.StatusCode);
                output.WriteLine("Response Body: " + response.RawContent);
            }

            catch (ApiException e)
            {
                output.WriteLine("Exception when calling SecureEmbeddedPremiumFinanceApi.SecureEpfQuotesBookingPut: " + e.Message);
                output.WriteLine("Status Code: " + e.ErrorCode);
                output.WriteLine(e.StackTrace);
            }
            //Assert.IsType<PFUpdatePFAResponse>(response);
        }

        /// <summary>
        /// Test SecureEpfQuotesCaptureesignPut
        /// </summary>
        [Fact]
        public void SecureEpfQuotesCaptureesignPutTest()
        {
            Configuration config = new()
            {
                BasePath = "https://api.uat.anddone.com"
            };

            var apiInstance = new SecureEmbeddedPremiumFinanceApi(config);
            using StreamReader r = new("C:\\Work\\AndDone_SDKs\\anddone-csharp-sdk-openapi-codegen\\config.json");
            dynamic jsonConfig = JObject.Parse(r.ReadToEnd());
            
            string xApiKey = jsonConfig.xApiKey;
            string xAppKey = jsonConfig.xAppKey;
            float xVersion = jsonConfig.xVersion;
            string origin = jsonConfig.origin;
            PFQuoteEsignRequest request = new(
                merchantToken: xAppKey,
                quoteKey: "29694517",
                insuredName: "John",
                ipAddress: "101.205.12.14",
                macAddress: "12-34-56-78-9A-BC",
                captchaToken: "rewgwgwehrtehwytrbwbtyjcxcvnt",
                actionName: ""
            );
            try
            {
                // This API will do return a quote for an existing policy or new policy for an existing account
                ApiResponse<object> response = apiInstance.SecureEpfQuotesCaptureesignPutWithHttpInfo(xApiKey, xAppKey, xVersion, origin, request);
                // output.WriteLine(response.Data.Title);
                output.WriteLine("Status Code: " + response.StatusCode);
                output.WriteLine("Response Body: " + response.RawContent);
            }

            catch (ApiException e)
            {
                output.WriteLine("Exception when calling SecureEmbeddedPremiumFinanceApi.SecureEpfQuotesCaptureesignPut: " + e.Message);
                output.WriteLine("Status Code: " + e.ErrorCode);
                output.WriteLine(e.StackTrace);
            }
        }

        /// <summary>
        /// Test SecureEpfQuotesGeneratePost
        /// </summary>
        [Fact]
        public void SecureEpfQuotesGeneratePostTest()
        {
            Configuration config = new()
            {
                BasePath = "https://api.uat.anddone.com"
            };

            var apiInstance = new SecureEmbeddedPremiumFinanceApi(config);
            using StreamReader r = new("C:\\Work\\AndDone_SDKs\\anddone-csharp-sdk-openapi-codegen\\config.json");
            dynamic jsonConfig = JObject.Parse(r.ReadToEnd());
            
            string xApiKey = jsonConfig.xApiKey;
            string xAppKey = jsonConfig.xAppKey;
            float xVersion = jsonConfig.xVersion;
            string origin = jsonConfig.origin;
            QuoteRequest request = new(
                paymentIntentId: "RdQkXMgx",
                details: new QuoteRequestDetails(
                    couponInvoicePrinted: false,
                    installments: 11,
                    programIDs: [82262],
                    commercial: null,
                    coupon: null,
                    interval: null,
                    downPaymentMethod: (QuoteRequestDetails.DownPaymentMethodEnum)1, // Take it from allow Transaction Type
                    downPaymentPaidBy: (QuoteRequestDetails.DownPaymentPaidByEnum)2
                ),
                insured: new QuoteRequestInsured(
                    agentCustomerNumber: "Suyash",
                    email: "test@test.com",
                    careOf: "",
                    uniqueId: xAppKey,
                    address: new QuoteRequestInsuredAddress(
                        name: "Sam",
                        address1: "1055 Broadway",
                        address2: "",
                        city: "Kansas City",
                        state: "KY",
                        zip: "64105",
                        phone: ""
                    )
                ),
                agent: new QuoteRequestAgent (
                    uniqueID: xAppKey,// Merchant Id
                    email: "test@test.com",
                    address: new QuoteRequestAgentAddress (
                        name: "Insurance Agency",
                        address1: "PO Box 486",
                        address2: "",
                        city: "Kansas City",
                        state: "KY",
                        zip: "64105",
                        phone: ""
                    )
                ),
                policies: new List<QuoteRequestPoliciesInner>([
                    new QuoteRequestPoliciesInner(
                        premium: 1000,
                        fee: 0,
                        tax: 0,
                        coverage: "FIRE",
                        effectiveDate: "2025-07-01T00:00:00",
                        expirationDate: "2026-07-01T00:00:00",
                        term: 12,
                        minimumEarned: 0,
                        minimumLiability: 0,
                        maximumLiability: 0,
                        invoiceNumber: "",
                        policyFees: [],
                        company: new QuoteRequestPoliciesInnerCompany (
                            bestNumber: "",
                            uniqueId: "LIC",
                            name: "LEXINGTON INSURANCE COMPANY",
                            address1: "",
                            address2: "",
                            city: "Kansas City",
                            state: "MO",
                            zip: "",
                            phone: ""
                        )
                    )
                ])
            );
            try
            {
                // This API will do return a quote for an existing policy or new policy for an existing account
                ApiResponse<List<PFGenerateQuoteResponse>> response = apiInstance.SecureEpfQuotesGeneratePostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, request);
                // output.WriteLine(response.Data.Title);
                output.WriteLine("Status Code: " + response.StatusCode);
                output.WriteLine("Response Body: " + response.RawContent);
            }

            catch (ApiException e)
            {
                output.WriteLine("Exception when calling SecureEmbeddedPremiumFinanceApi.SecureEpfQuotesGeneratePost: " + e.Message);
                output.WriteLine("Status Code: " + e.ErrorCode);
                output.WriteLine(e.StackTrace);
            }
            //Assert.IsType<List<PFGenerateQuoteResponse>>(response);
        }

        /// <summary>
        /// Test SecureEpfQuotesIntentPost
        /// </summary>
        [Fact]
        public void SecureEpfQuotesIntentPostTest()
        {
            Configuration config = new()
            {
                BasePath = "https://api.uat.anddone.com"
            };

            var apiInstance = new SecureEmbeddedPremiumFinanceApi(config);
            using StreamReader r = new("C:\\Work\\AndDone_SDKs\\anddone-csharp-sdk-openapi-codegen\\config.json");
            dynamic jsonConfig = JObject.Parse(r.ReadToEnd());
            
            string xApiKey = jsonConfig.xApiKey;
            string xAppKey = jsonConfig.xAppKey;
            float xVersion = jsonConfig.xVersion;
            string origin = jsonConfig.origin;
            GetQuoteRequest request = new(
                paymentIntentId: "RdQkXMgx"
            );
            try
            {
                // This API will do return a quote for an existing policy or new policy for an existing account
                ApiResponse<List<QuoteResponse>> response = apiInstance.SecureEpfQuotesIntentPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, request);
                // output.WriteLine(response.Data.Title);
                output.WriteLine("Status Code: " + response.StatusCode);
                output.WriteLine("Response Body: " + response.RawContent);
            }

            catch (ApiException e)
            {
                output.WriteLine("Exception when calling SecureEmbeddedPremiumFinanceApi.SecureEpfQuotesIntentPost: " + e.Message);
                output.WriteLine("Status Code: " + e.ErrorCode);
                output.WriteLine(e.StackTrace);
            }
            //Assert.IsType<List<QuoteResponse>>(response);
        }

        /// <summary>
        /// Test SecureEpfQuotesPost
        /// </summary>
        [Fact]
        public void SecureEpfQuotesPostTest()
        {
            Configuration config = new()
            {
                BasePath = "https://api.uat.anddone.com"
            };

            var apiInstance = new SecureEmbeddedPremiumFinanceApi(config);
            using StreamReader r = new("C:\\Work\\AndDone_SDKs\\anddone-csharp-sdk-openapi-codegen\\config.json");
            dynamic jsonConfig = JObject.Parse(r.ReadToEnd());
            
            string xApiKey = jsonConfig.xApiKey;
            string xAppKey = jsonConfig.xAppKey;
            float xVersion = jsonConfig.xVersion;
            string origin = jsonConfig.origin;
            GetQuoteKeyRequest request = new(
                quoteKey: "29694517"
            );
            try
            {
                // This API will do return a quote for an existing policy or new policy for an existing account
                ApiResponse<QuoteResponse> response = apiInstance.SecureEpfQuotesPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, request);
                // output.WriteLine(response.Data.Title);
                output.WriteLine("Status Code: " + response.StatusCode);
                output.WriteLine("Response Body: " + response.RawContent);
            }

            catch (ApiException e)
            {
                output.WriteLine("Exception when calling SecureEmbeddedPremiumFinanceApi.SecureEpfQuotesPost: " + e.Message);
                output.WriteLine("Status Code: " + e.ErrorCode);
                output.WriteLine(e.StackTrace);
            }
            //Assert.IsType<QuoteResponse>(response);
        }

        /// <summary>
        /// Test SecureEpfRetrievepfaPost
        /// </summary>
        [Fact]
        public void SecureEpfRetrievepfaPostTest()
        {
            Configuration config = new()
            {
                BasePath = "https://api.uat.anddone.com"
            };

            var apiInstance = new SecureEmbeddedPremiumFinanceApi(config);
            using StreamReader r = new("C:\\Work\\AndDone_SDKs\\anddone-csharp-sdk-openapi-codegen\\config.json");
            dynamic jsonConfig = JObject.Parse(r.ReadToEnd());
            
            string xApiKey = jsonConfig.xApiKey;
            string xAppKey = jsonConfig.xAppKey;
            float xVersion = jsonConfig.xVersion;
            string origin = jsonConfig.origin;
            PFRetrievePFARequestDTO request = new(
                quoteKey: "29694517"
            );
            try
            {
                // This API will do return a quote for an existing policy or new policy for an existing account
                ApiResponse<string> response = apiInstance.SecureEpfRetrievepfaPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, request);
                // output.WriteLine(response.Data.Title);
                output.WriteLine("Status Code: " + response.StatusCode);
                output.WriteLine("Response Body: " + response.RawContent);
            }

            catch (ApiException e)
            {
                output.WriteLine("Exception when calling SecureEmbeddedPremiumFinanceApi.SecureEpfRetrievepfaPost: " + e.Message);
                output.WriteLine("Status Code: " + e.ErrorCode);
                output.WriteLine(e.StackTrace);
            }
            //Assert.IsType<string>(response);
        }
    }
}
