/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SecurePaymentBatchingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SecurePaymentBatchingApiTests : IDisposable
    {
        private SecurePaymentBatchingApi instance;

        public SecurePaymentBatchingApiTests()
        {
            instance = new SecurePaymentBatchingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecurePaymentBatchingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SecurePaymentBatchingApi
            //Assert.IsType<SecurePaymentBatchingApi>(instance);
        }

        /// <summary>
        /// Test SecureBatchesDetailsPost
        /// </summary>
        [Fact]
        public void SecureBatchesDetailsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //decimal xVersion = null;
            //string origin = null;
            //SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest = null;
            //var response = instance.SecureBatchesDetailsPost(xApiKey, xAppKey, xVersion, origin, securePaymentBatchDetailsRequest);
            //Assert.IsType<List<PaymentBatchDetailsResponse>>(response);
        }

        /// <summary>
        /// Test SecureBatchesExecutePost
        /// </summary>
        [Fact]
        public void SecureBatchesExecutePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //decimal xVersion = null;
            //string origin = null;
            //SecureBatchExecuteRequest secureBatchExecuteRequest = null;
            //instance.SecureBatchesExecutePost(xApiKey, xAppKey, xVersion, origin, secureBatchExecuteRequest);
        }

        /// <summary>
        /// Test SecureBatchesPost
        /// </summary>
        [Fact]
        public void SecureBatchesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //decimal xVersion = null;
            //string origin = null;
            //int? startRow = null;
            //int? pageSize = null;
            //string? sortField = null;
            //bool? asc = null;
            //var response = instance.SecureBatchesPost(xApiKey, xAppKey, xVersion, origin, startRow, pageSize, sortField, asc);
            //Assert.IsType<PaymentBatchResponse>(response);
        }

        /// <summary>
        /// Test SecureBatchesTimelinesPost
        /// </summary>
        [Fact]
        public void SecureBatchesTimelinesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //decimal xVersion = null;
            //string origin = null;
            //SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest = null;
            //var response = instance.SecureBatchesTimelinesPost(xApiKey, xAppKey, xVersion, origin, securePaymentBatchDetailsRequest);
            //Assert.IsType<List<PaymentBatchEventLogResponse>>(response);
        }

        /// <summary>
        /// Test SecureBatchesTransactionsCancelPost
        /// </summary>
        [Fact]
        public void SecureBatchesTransactionsCancelPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //decimal xVersion = null;
            //string origin = null;
            //PaymentBatchCancellationRequest paymentBatchCancellationRequest = null;
            //instance.SecureBatchesTransactionsCancelPost(xApiKey, xAppKey, xVersion, origin, paymentBatchCancellationRequest);
        }
    }
}
