/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
using Org.OpenAPITools.Model;
using Xunit.Abstractions;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SecureOrumApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SecureOrumApiTests(ITestOutputHelper output) : IDisposable
    {
        private SecureOrumApi instance = new();
        private readonly ITestOutputHelper output = output;

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureOrumApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SecureOrumApi
            //Assert.IsType<SecureOrumApi>(instance);
        }

        /// <summary>
        /// Test SecureBankaccountsDetailsPost
        /// </summary>
        [Fact]
        public void SecureBankaccountsDetailsPostTest()
        {
            Configuration config = new()
            {
                BasePath = "https://api.uat.anddone.com"
            };

            var apiInstance = new SecureOrumApi(config);
            var xApiKey = "T3Hj93GzbuhMLiNQg/yJ/yNArhFJeEHoSLyFZ9IBQkY=";  // string | an authorization header
            var xAppKey = "bdYqRMdn";  // string | an authorization header
            var origin = "136.34.79.196/32";  // string | an authorization header. Your origin IP address or URL. Must be configured with AndDone Administration
            var xVersion = 2.3F;  // string | x-version
            VerificationEntityRequest request = new(
                id: "220a5d64-b9c7-46c8-adb2-c13fe66abcb2"
            );
            try
            {
                // This API will do return a quote for an existing policy or new policy for an existing account
                ApiResponse<List<VerifyBankAccountResponse>> response = apiInstance.SecureBankaccountsDetailsPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, null, null, request);
                // output.WriteLine(response.Data.Title);
                output.WriteLine("Status Code: " + response.StatusCode);
                output.WriteLine("Response Body: " + response.RawContent);
            }

            catch (ApiException e)
            {
                output.WriteLine("Exception when calling SecureOrumApi.SecureBankaccountsDetailsPost: " + e.Message);
                output.WriteLine("Status Code: " + e.ErrorCode);
                output.WriteLine(e.StackTrace);
            }
            //Assert.IsType<List<VerifyBankAccountResponse>>(response);
        }

        /// <summary>
        /// Test SecureBankaccountsVerifyPost
        /// </summary>
        [Fact]
        public void SecureBankaccountsVerifyPostTest()
        {
            Configuration config = new()
            {
                BasePath = "https://api.uat.anddone.com"
            };

            var apiInstance = new SecureOrumApi(config);
            var xApiKey = "T3Hj93GzbuhMLiNQg/yJ/yNArhFJeEHoSLyFZ9IBQkY=";  // string | an authorization header
            var xAppKey = "bdYqRMdn";  // string | an authorization header
            var origin = "136.34.79.196/32";  // string | an authorization header. Your origin IP address or URL. Must be configured with AndDone Administration
            var xVersion = 2.3F;  // string | x-version
            VerifyBankAccountRequest request = new(
                accountNumber: "123456780",
                routingNumber: "121000358",
                accountHolderName: "John Doe",
                statementDisplayName: "Johns Account",
                bankAccountEntity: new VerifyBankAccountRequestBankAccountEntity(
                    id: 1,
                    type: "Vendor"
                )
            );
            try
            {
                // This API will do return a quote for an existing policy or new policy for an existing account
                ApiResponse<List<VerifyBankAccountResponse>> response = apiInstance.SecureBankaccountsVerifyPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, request);
                // output.WriteLine(response.Data.Title);
                output.WriteLine("Status Code: " + response.StatusCode);
                output.WriteLine("Response Body: " + response.RawContent);
            }

            catch (ApiException e)
            {
                output.WriteLine("Exception when calling SecureOrumApi.SecureBankaccountsVerifyPost: " + e.Message);
                output.WriteLine("Status Code: " + e.ErrorCode);
                output.WriteLine(e.StackTrace);
            }
            //Assert.IsType<List<VerifyBankAccountResponse>>(response);
        }
    }
}
