/*
 * Secure API
 *
 * Secure API's
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SecureEmbeddedPremiumFinanceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SecureEmbeddedPremiumFinanceApiTests : IDisposable
    {
        private SecureEmbeddedPremiumFinanceApi instance;

        public SecureEmbeddedPremiumFinanceApiTests()
        {
            instance = new SecureEmbeddedPremiumFinanceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureEmbeddedPremiumFinanceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SecureEmbeddedPremiumFinanceApi
            //Assert.IsType<SecureEmbeddedPremiumFinanceApi>(instance);
        }

        /// <summary>
        /// Test SecureMerchantsEpfQuotesPolicyPut
        /// </summary>
        [Fact]
        public void SecureMerchantsEpfQuotesPolicyPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //string origin = null;
            //string xVersion = null;
            //string parentId = null;
            //PFPolicyUpdateRequestDTO policyUpdateRequest = null;
            //instance.SecureMerchantsEpfQuotesPolicyPut(xApiKey, xAppKey, origin, xVersion, parentId, policyUpdateRequest);
        }

        /// <summary>
        /// Test SecureTokensActivationsPost
        /// </summary>
        [Fact]
        public void SecureTokensActivationsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //string origin = null;
            //string xVersion = null;
            //GetQuoteRequest quoteRequest = null;
            //var response = instance.SecureTokensActivationsPost(xApiKey, xAppKey, origin, xVersion, quoteRequest);
            //Assert.IsType<Object>(response);
        }
    }
}
