# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.payment_request_billing_contact import PaymentRequestBillingContact
from openapi_client.models.payment_request_customer_indentity_request import PaymentRequestCustomerIndentityRequest
from openapi_client.models.payment_request_pfr import PaymentRequestPFR
from openapi_client.models.payment_request_splits_inner import PaymentRequestSplitsInner
from openapi_client.models.payment_request_tender_info import PaymentRequestTenderInfo
from typing import Optional, Set
from typing_extensions import Self

class PaymentRequest(BaseModel):
    """
    PaymentRequest
    """ # noqa: E501
    token: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    transaction_code: Optional[StrictStr] = Field(default=None, alias="transactionCode")
    billing_contact: Optional[PaymentRequestBillingContact] = Field(default=None, alias="billingContact")
    phone_country_code: Optional[StrictStr] = Field(default=None, alias="phoneCountryCode")
    channel_type: Optional[StrictStr] = Field(default=None, alias="channelType")
    tender_info: Optional[PaymentRequestTenderInfo] = Field(default=None, alias="tenderInfo")
    customer_id: Optional[StrictStr] = Field(default=None, alias="customerId")
    customer_indentity_request: Optional[PaymentRequestCustomerIndentityRequest] = Field(default=None, alias="customerIndentityRequest")
    invoice_no: Optional[StrictStr] = Field(default=None, alias="invoiceNo")
    po_no: Optional[StrictStr] = Field(default=None, alias="poNo")
    reference_no: Optional[StrictStr] = Field(default=None, alias="referenceNo")
    payment_reference: Optional[StrictStr] = Field(default=None, alias="paymentReference")
    remarks: Optional[StrictStr] = None
    save_customer: Optional[StrictBool] = Field(default=None, alias="saveCustomer")
    captcha_token: Optional[StrictStr] = Field(default=None, alias="captchaToken")
    action_name: Optional[StrictStr] = Field(default=None, alias="actionName")
    additional_fields: Optional[Dict[str, StrictStr]] = Field(default=None, alias="additionalFields")
    wait_for_approval: Optional[StrictBool] = Field(default=None, alias="waitForApproval")
    issuer: Optional[StrictStr] = None
    splits: Optional[List[PaymentRequestSplitsInner]] = None
    operation_type: Optional[StrictStr] = Field(default=None, alias="operationType")
    suppress_technology_fee: Optional[StrictBool] = Field(default=None, alias="suppressTechnologyFee")
    override_technology_fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="overrideTechnologyFee")
    is_premium_financier: Optional[StrictBool] = Field(default=None, alias="isPremiumFinancier")
    p_fr: Optional[PaymentRequestPFR] = Field(default=None, alias="pFR")
    __properties: ClassVar[List[str]] = ["token", "type", "transactionCode", "billingContact", "phoneCountryCode", "channelType", "tenderInfo", "customerId", "customerIndentityRequest", "invoiceNo", "poNo", "referenceNo", "paymentReference", "remarks", "saveCustomer", "captchaToken", "actionName", "additionalFields", "waitForApproval", "issuer", "splits", "operationType", "suppressTechnologyFee", "overrideTechnologyFee", "isPremiumFinancier", "pFR"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['AnytimePayment', 'SubDomain', 'PaymentIntent', 'PaymentLink', 'OpenPayment', 'TokenLink']):
            raise ValueError("must be one of enum values ('AnytimePayment', 'SubDomain', 'PaymentIntent', 'PaymentLink', 'OpenPayment', 'TokenLink')")
        return value

    @field_validator('channel_type')
    def channel_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CreditCard', 'DebitCard', 'ACH']):
            raise ValueError("must be one of enum values ('CreditCard', 'DebitCard', 'ACH')")
        return value

    @field_validator('operation_type')
    def operation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Sale', 'VerifyOnly', 'ForceSale', 'Adjust', 'Activate', 'Deactivate', 'Reload', 'Refund', 'Inquire', 'ReverseAuth']):
            raise ValueError("must be one of enum values ('Sale', 'VerifyOnly', 'ForceSale', 'Adjust', 'Activate', 'Deactivate', 'Reload', 'Refund', 'Inquire', 'ReverseAuth')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of billing_contact
        if self.billing_contact:
            _dict['billingContact'] = self.billing_contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tender_info
        if self.tender_info:
            _dict['tenderInfo'] = self.tender_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customer_indentity_request
        if self.customer_indentity_request:
            _dict['customerIndentityRequest'] = self.customer_indentity_request.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in splits (list)
        _items = []
        if self.splits:
            for _item_splits in self.splits:
                if _item_splits:
                    _items.append(_item_splits.to_dict())
            _dict['splits'] = _items
        # override the default output from pydantic by calling `to_dict()` of p_fr
        if self.p_fr:
            _dict['pFR'] = self.p_fr.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "token": obj.get("token"),
            "type": obj.get("type"),
            "transactionCode": obj.get("transactionCode"),
            "billingContact": PaymentRequestBillingContact.from_dict(obj["billingContact"]) if obj.get("billingContact") is not None else None,
            "phoneCountryCode": obj.get("phoneCountryCode"),
            "channelType": obj.get("channelType"),
            "tenderInfo": PaymentRequestTenderInfo.from_dict(obj["tenderInfo"]) if obj.get("tenderInfo") is not None else None,
            "customerId": obj.get("customerId"),
            "customerIndentityRequest": PaymentRequestCustomerIndentityRequest.from_dict(obj["customerIndentityRequest"]) if obj.get("customerIndentityRequest") is not None else None,
            "invoiceNo": obj.get("invoiceNo"),
            "poNo": obj.get("poNo"),
            "referenceNo": obj.get("referenceNo"),
            "paymentReference": obj.get("paymentReference"),
            "remarks": obj.get("remarks"),
            "saveCustomer": obj.get("saveCustomer"),
            "captchaToken": obj.get("captchaToken"),
            "actionName": obj.get("actionName"),
            "additionalFields": obj.get("additionalFields"),
            "waitForApproval": obj.get("waitForApproval"),
            "issuer": obj.get("issuer"),
            "splits": [PaymentRequestSplitsInner.from_dict(_item) for _item in obj["splits"]] if obj.get("splits") is not None else None,
            "operationType": obj.get("operationType"),
            "suppressTechnologyFee": obj.get("suppressTechnologyFee"),
            "overrideTechnologyFee": obj.get("overrideTechnologyFee"),
            "isPremiumFinancier": obj.get("isPremiumFinancier"),
            "pFR": PaymentRequestPFR.from_dict(obj["pFR"]) if obj.get("pFR") is not None else None
        })
        return _obj


