# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PaymentRequestTenderInfo(BaseModel):
    """
    PaymentRequestTenderInfo
    """ # noqa: E501
    bank_name: Optional[StrictStr] = Field(default=None, alias="bankName")
    account_number: Optional[StrictStr] = Field(default=None, alias="accountNumber")
    routing_number: Optional[StrictStr] = Field(default=None, alias="routingNumber")
    raw_micr_line: Optional[StrictStr] = Field(default=None, alias="rawMICRLine")
    account_type: Optional[StrictStr] = Field(default=None, alias="accountType")
    check_number: Optional[StrictStr] = Field(default=None, alias="checkNumber")
    account_category: Optional[StrictStr] = Field(default=None, alias="accountCategory")
    account_holder_name: Optional[StrictStr] = Field(default=None, alias="accountHolderName")
    name_on_check: Optional[StrictStr] = Field(default=None, alias="nameOnCheck")
    card_holder_name: Optional[StrictStr] = Field(default=None, alias="cardHolderName")
    card_type: Optional[StrictStr] = Field(default=None, alias="cardType")
    card_number: Optional[StrictStr] = Field(default=None, alias="cardNumber")
    card_expiry: Optional[StrictStr] = Field(default=None, alias="cardExpiry")
    c_v_data: Optional[StrictStr] = Field(default=None, alias="cVData")
    c_v_data_status: Optional[StrictStr] = Field(default=None, alias="cVDataStatus")
    track_data: Optional[StrictStr] = Field(default=None, alias="trackData")
    health_care_account_type: Optional[StrictStr] = Field(default=None, alias="healthCareAccountType")
    rx_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="rxAmount")
    vision_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="visionAmount")
    dental_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="dentalAmount")
    clinic_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="clinicAmount")
    remove_discounting: Optional[StrictBool] = Field(default=None, alias="removeDiscounting")
    suppress_commission: Optional[StrictBool] = Field(default=None, alias="suppressCommission")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    tip_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="tipAmount")
    convenience_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="convenienceAmount")
    tax_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="taxAmount")
    tax_percent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="taxPercent")
    tax_after_discount: Optional[StrictBool] = Field(default=None, alias="taxAfterDiscount")
    pre_auth_code: Optional[StrictStr] = Field(default=None, alias="preAuthCode")
    create_account_token: Optional[StrictBool] = Field(default=None, alias="createAccountToken")
    account_token: Optional[StrictStr] = Field(default=None, alias="accountToken")
    discount_type: Optional[StrictStr] = Field(default=None, alias="discountType")
    discount_percent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="discountPercent")
    discount_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="discountAmount")
    __properties: ClassVar[List[str]] = ["bankName", "accountNumber", "routingNumber", "rawMICRLine", "accountType", "checkNumber", "accountCategory", "accountHolderName", "nameOnCheck", "cardHolderName", "cardType", "cardNumber", "cardExpiry", "cVData", "cVDataStatus", "trackData", "healthCareAccountType", "rxAmount", "visionAmount", "dentalAmount", "clinicAmount", "removeDiscounting", "suppressCommission", "amount", "tipAmount", "convenienceAmount", "taxAmount", "taxPercent", "taxAfterDiscount", "preAuthCode", "createAccountToken", "accountToken", "discountType", "discountPercent", "discountAmount"]

    @field_validator('account_category')
    def account_category_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Unknown', 'Personal', 'Business']):
            raise ValueError("must be one of enum values ('Unknown', 'Personal', 'Business')")
        return value

    @field_validator('discount_type')
    def discount_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Fixed', 'Percentage']):
            raise ValueError("must be one of enum values ('Fixed', 'Percentage')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentRequestTenderInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentRequestTenderInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bankName": obj.get("bankName"),
            "accountNumber": obj.get("accountNumber"),
            "routingNumber": obj.get("routingNumber"),
            "rawMICRLine": obj.get("rawMICRLine"),
            "accountType": obj.get("accountType"),
            "checkNumber": obj.get("checkNumber"),
            "accountCategory": obj.get("accountCategory"),
            "accountHolderName": obj.get("accountHolderName"),
            "nameOnCheck": obj.get("nameOnCheck"),
            "cardHolderName": obj.get("cardHolderName"),
            "cardType": obj.get("cardType"),
            "cardNumber": obj.get("cardNumber"),
            "cardExpiry": obj.get("cardExpiry"),
            "cVData": obj.get("cVData"),
            "cVDataStatus": obj.get("cVDataStatus"),
            "trackData": obj.get("trackData"),
            "healthCareAccountType": obj.get("healthCareAccountType"),
            "rxAmount": obj.get("rxAmount"),
            "visionAmount": obj.get("visionAmount"),
            "dentalAmount": obj.get("dentalAmount"),
            "clinicAmount": obj.get("clinicAmount"),
            "removeDiscounting": obj.get("removeDiscounting"),
            "suppressCommission": obj.get("suppressCommission"),
            "amount": obj.get("amount"),
            "tipAmount": obj.get("tipAmount"),
            "convenienceAmount": obj.get("convenienceAmount"),
            "taxAmount": obj.get("taxAmount"),
            "taxPercent": obj.get("taxPercent"),
            "taxAfterDiscount": obj.get("taxAfterDiscount"),
            "preAuthCode": obj.get("preAuthCode"),
            "createAccountToken": obj.get("createAccountToken"),
            "accountToken": obj.get("accountToken"),
            "discountType": obj.get("discountType"),
            "discountPercent": obj.get("discountPercent"),
            "discountAmount": obj.get("discountAmount")
        })
        return _obj


