# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.pf_check_endorsements_response_item_policies_inner import PFCheckEndorsementsResponseItemPoliciesInner
from typing import Optional, Set
from typing_extensions import Self

class PFCheckEndorsementsResponseItem(BaseModel):
    """
    PFCheckEndorsementsResponseItem
    """ # noqa: E501
    agreement_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="AgreementID")
    client_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="ClientID")
    account_number: Optional[StrictStr] = Field(default=None, alias="AccountNumber")
    client_name: Optional[StrictStr] = Field(default=None, alias="ClientName")
    is_commercial: Optional[StrictBool] = Field(default=None, alias="IsCommercial")
    policies: Optional[List[PFCheckEndorsementsResponseItemPoliciesInner]] = None
    __properties: ClassVar[List[str]] = ["AgreementID", "ClientID", "AccountNumber", "ClientName", "IsCommercial", "policies"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFCheckEndorsementsResponseItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in policies (list)
        _items = []
        if self.policies:
            for _item_policies in self.policies:
                if _item_policies:
                    _items.append(_item_policies.to_dict())
            _dict['policies'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFCheckEndorsementsResponseItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AgreementID": obj.get("AgreementID"),
            "ClientID": obj.get("ClientID"),
            "AccountNumber": obj.get("AccountNumber"),
            "ClientName": obj.get("ClientName"),
            "IsCommercial": obj.get("IsCommercial"),
            "policies": [PFCheckEndorsementsResponseItemPoliciesInner.from_dict(_item) for _item in obj["policies"]] if obj.get("policies") is not None else None
        })
        return _obj


