# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.payment_request_billing_contact import PaymentRequestBillingContact
from openapi_client.models.secure_transaction_detail_dto_tender_info import SecureTransactionDetailDTOTenderInfo
from openapi_client.models.transaction_detail_response_transaction_result import TransactionDetailResponseTransactionResult
from typing import Optional, Set
from typing_extensions import Self

class SecureTransactionDetailDTO(BaseModel):
    """
    SecureTransactionDetailDTO
    """ # noqa: E501
    transaction_id: Optional[StrictStr] = Field(default=None, alias="transactionId")
    trace_number: Optional[StrictStr] = Field(default=None, alias="traceNumber")
    transaction_code: Optional[StrictStr] = Field(default=None, alias="transactionCode")
    transaction_origin: Optional[StrictStr] = Field(default=None, alias="transactionOrigin")
    billing_contact: Optional[PaymentRequestBillingContact] = Field(default=None, alias="billingContact")
    shipping_contact: Optional[PaymentRequestBillingContact] = Field(default=None, alias="shippingContact")
    reference_transaction_id: Optional[StrictStr] = Field(default=None, alias="referenceTransactionId")
    transaction_date: Optional[StrictStr] = Field(default=None, alias="transactionDate")
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    ip_address: Optional[StrictStr] = Field(default=None, alias="ipAddress")
    operation_type: Optional[StrictStr] = Field(default=None, alias="operationType")
    channel_type: Optional[StrictStr] = Field(default=None, alias="channelType")
    process_method: Optional[StrictStr] = Field(default=None, alias="processMethod")
    processor_name: Optional[StrictStr] = Field(default=None, alias="processorName")
    is_debit: Optional[StrictBool] = Field(default=None, alias="isDebit")
    tender_info: Optional[SecureTransactionDetailDTOTenderInfo] = Field(default=None, alias="tenderInfo")
    reference_customer_id: Optional[StrictInt] = Field(default=None, alias="referenceCustomerId")
    masked_reference_customer_id: Optional[StrictStr] = Field(default=None, alias="maskedReferenceCustomerId")
    customer_account_id: Optional[StrictInt] = Field(default=None, alias="customerAccountId")
    masked_customer_account_id: Optional[StrictStr] = Field(default=None, alias="maskedCustomerAccountId")
    invoice_no: Optional[StrictStr] = Field(default=None, alias="invoiceNo")
    po_no: Optional[StrictStr] = Field(default=None, alias="poNo")
    reference_no: Optional[StrictStr] = Field(default=None, alias="referenceNo")
    remarks: Optional[StrictStr] = None
    recurring_type: Optional[StrictStr] = Field(default=None, alias="recurringType")
    recurring_id: Optional[StrictInt] = Field(default=None, alias="recurringId")
    masked_recurring_id: Optional[StrictStr] = Field(default=None, alias="maskedRecurringId")
    installment_number: Optional[StrictInt] = Field(default=None, alias="installmentNumber")
    installment_count: Optional[StrictInt] = Field(default=None, alias="installmentCount")
    allow_duplicates: Optional[StrictBool] = Field(default=None, alias="allowDuplicates")
    verification_enabled: Optional[StrictBool] = Field(default=None, alias="verificationEnabled")
    sent_success_notification: Optional[StrictBool] = Field(default=None, alias="sentSuccessNotification")
    sent_failed_notification: Optional[StrictBool] = Field(default=None, alias="sentFailedNotification")
    training_mode: Optional[StrictBool] = Field(default=None, alias="trainingMode")
    terminal_id: Optional[StrictStr] = Field(default=None, alias="terminalId")
    is_offline: Optional[StrictBool] = Field(default=None, alias="isOffline")
    transaction_status: Optional[StrictStr] = Field(default=None, alias="transactionStatus")
    previous_transaction_status: Optional[StrictStr] = Field(default=None, alias="previousTransactionStatus")
    transaction_result: Optional[TransactionDetailResponseTransactionResult] = Field(default=None, alias="transactionResult")
    level: Optional[StrictInt] = None
    partner_id: Optional[StrictInt] = Field(default=None, alias="partnerId")
    masked_partner_id: Optional[StrictStr] = Field(default=None, alias="maskedPartnerId")
    order_id: Optional[StrictInt] = Field(default=None, alias="orderId")
    masked_order_id: Optional[StrictStr] = Field(default=None, alias="maskedOrderId")
    invoice_id: Optional[StrictStr] = Field(default=None, alias="invoiceId")
    masked_invoice_id: Optional[StrictStr] = Field(default=None, alias="maskedInvoiceId")
    payment_link_id: Optional[StrictStr] = Field(default=None, alias="paymentLinkId")
    masked_payment_link_id: Optional[StrictStr] = Field(default=None, alias="maskedPaymentLinkId")
    additional_fields: Optional[StrictStr] = Field(default=None, alias="additionalFields")
    settlement_date: Optional[StrictStr] = Field(default=None, alias="settlementDate")
    issuer: Optional[StrictStr] = None
    payment_reference: Optional[StrictStr] = Field(default=None, alias="paymentReference")
    refund_reference: Optional[StrictStr] = Field(default=None, alias="refundReference")
    __properties: ClassVar[List[str]] = ["transactionId", "traceNumber", "transactionCode", "transactionOrigin", "billingContact", "shippingContact", "referenceTransactionId", "transactionDate", "merchantId", "ipAddress", "operationType", "channelType", "processMethod", "processorName", "isDebit", "tenderInfo", "referenceCustomerId", "maskedReferenceCustomerId", "customerAccountId", "maskedCustomerAccountId", "invoiceNo", "poNo", "referenceNo", "remarks", "recurringType", "recurringId", "maskedRecurringId", "installmentNumber", "installmentCount", "allowDuplicates", "verificationEnabled", "sentSuccessNotification", "sentFailedNotification", "trainingMode", "terminalId", "isOffline", "transactionStatus", "previousTransactionStatus", "transactionResult", "level", "partnerId", "maskedPartnerId", "orderId", "maskedOrderId", "invoiceId", "maskedInvoiceId", "paymentLinkId", "maskedPaymentLinkId", "additionalFields", "settlementDate", "issuer", "paymentReference", "refundReference"]

    @field_validator('transaction_origin')
    def transaction_origin_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Terminal', 'VirtualTerminal', 'WebForm', 'API', 'Schedule', 'Batch', 'PaymentIntent']):
            raise ValueError("must be one of enum values ('Terminal', 'VirtualTerminal', 'WebForm', 'API', 'Schedule', 'Batch', 'PaymentIntent')")
        return value

    @field_validator('operation_type')
    def operation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Sale', 'VerifyOnly', 'ForceSale', 'Adjust', 'Activate', 'Deactivate', 'Reload', 'Refund', 'Inquire', 'ReverseAuth']):
            raise ValueError("must be one of enum values ('Sale', 'VerifyOnly', 'ForceSale', 'Adjust', 'Activate', 'Deactivate', 'Reload', 'Refund', 'Inquire', 'ReverseAuth')")
        return value

    @field_validator('channel_type')
    def channel_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NotDefined', 'ACH', 'CreditCard', 'DebitCard']):
            raise ValueError("must be one of enum values ('NotDefined', 'ACH', 'CreditCard', 'DebitCard')")
        return value

    @field_validator('process_method')
    def process_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NotDefined', 'ACH', 'CardNotPresent']):
            raise ValueError("must be one of enum values ('NotDefined', 'ACH', 'CardNotPresent')")
        return value

    @field_validator('recurring_type')
    def recurring_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Installment', 'Billing', 'Custom']):
            raise ValueError("must be one of enum values ('Installment', 'Billing', 'Custom')")
        return value

    @field_validator('transaction_status')
    def transaction_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'ChargebackReversed', 'RefundedReversed', 'Paid', 'PaidChargeback', 'PaidChargebackReversed', 'PaidRefunded', 'PaidRefundedReversed', 'None', 'Unknown']):
            raise ValueError("must be one of enum values ('Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'ChargebackReversed', 'RefundedReversed', 'Paid', 'PaidChargeback', 'PaidChargebackReversed', 'PaidRefunded', 'PaidRefundedReversed', 'None', 'Unknown')")
        return value

    @field_validator('previous_transaction_status')
    def previous_transaction_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'ChargebackReversed', 'RefundedReversed', 'Paid', 'PaidChargeback', 'PaidChargebackReversed', 'PaidRefunded', 'PaidRefundedReversed', 'None', 'Unknown']):
            raise ValueError("must be one of enum values ('Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'ChargebackReversed', 'RefundedReversed', 'Paid', 'PaidChargeback', 'PaidChargebackReversed', 'PaidRefunded', 'PaidRefundedReversed', 'None', 'Unknown')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SecureTransactionDetailDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of billing_contact
        if self.billing_contact:
            _dict['billingContact'] = self.billing_contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipping_contact
        if self.shipping_contact:
            _dict['shippingContact'] = self.shipping_contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tender_info
        if self.tender_info:
            _dict['tenderInfo'] = self.tender_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transaction_result
        if self.transaction_result:
            _dict['transactionResult'] = self.transaction_result.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SecureTransactionDetailDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transactionId": obj.get("transactionId"),
            "traceNumber": obj.get("traceNumber"),
            "transactionCode": obj.get("transactionCode"),
            "transactionOrigin": obj.get("transactionOrigin"),
            "billingContact": PaymentRequestBillingContact.from_dict(obj["billingContact"]) if obj.get("billingContact") is not None else None,
            "shippingContact": PaymentRequestBillingContact.from_dict(obj["shippingContact"]) if obj.get("shippingContact") is not None else None,
            "referenceTransactionId": obj.get("referenceTransactionId"),
            "transactionDate": obj.get("transactionDate"),
            "merchantId": obj.get("merchantId"),
            "ipAddress": obj.get("ipAddress"),
            "operationType": obj.get("operationType"),
            "channelType": obj.get("channelType"),
            "processMethod": obj.get("processMethod"),
            "processorName": obj.get("processorName"),
            "isDebit": obj.get("isDebit"),
            "tenderInfo": SecureTransactionDetailDTOTenderInfo.from_dict(obj["tenderInfo"]) if obj.get("tenderInfo") is not None else None,
            "referenceCustomerId": obj.get("referenceCustomerId"),
            "maskedReferenceCustomerId": obj.get("maskedReferenceCustomerId"),
            "customerAccountId": obj.get("customerAccountId"),
            "maskedCustomerAccountId": obj.get("maskedCustomerAccountId"),
            "invoiceNo": obj.get("invoiceNo"),
            "poNo": obj.get("poNo"),
            "referenceNo": obj.get("referenceNo"),
            "remarks": obj.get("remarks"),
            "recurringType": obj.get("recurringType"),
            "recurringId": obj.get("recurringId"),
            "maskedRecurringId": obj.get("maskedRecurringId"),
            "installmentNumber": obj.get("installmentNumber"),
            "installmentCount": obj.get("installmentCount"),
            "allowDuplicates": obj.get("allowDuplicates"),
            "verificationEnabled": obj.get("verificationEnabled"),
            "sentSuccessNotification": obj.get("sentSuccessNotification"),
            "sentFailedNotification": obj.get("sentFailedNotification"),
            "trainingMode": obj.get("trainingMode"),
            "terminalId": obj.get("terminalId"),
            "isOffline": obj.get("isOffline"),
            "transactionStatus": obj.get("transactionStatus"),
            "previousTransactionStatus": obj.get("previousTransactionStatus"),
            "transactionResult": TransactionDetailResponseTransactionResult.from_dict(obj["transactionResult"]) if obj.get("transactionResult") is not None else None,
            "level": obj.get("level"),
            "partnerId": obj.get("partnerId"),
            "maskedPartnerId": obj.get("maskedPartnerId"),
            "orderId": obj.get("orderId"),
            "maskedOrderId": obj.get("maskedOrderId"),
            "invoiceId": obj.get("invoiceId"),
            "maskedInvoiceId": obj.get("maskedInvoiceId"),
            "paymentLinkId": obj.get("paymentLinkId"),
            "maskedPaymentLinkId": obj.get("maskedPaymentLinkId"),
            "additionalFields": obj.get("additionalFields"),
            "settlementDate": obj.get("settlementDate"),
            "issuer": obj.get("issuer"),
            "paymentReference": obj.get("paymentReference"),
            "refundReference": obj.get("refundReference")
        })
        return _obj


