/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecurePaymentBatchingApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// This API is used for getting Secure Payment Batch Details
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Secure Payment Batch Details Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentBatchDetailsResponse&gt;</returns>
        List<PaymentBatchDetailsResponse> SecureBatchesDetailsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0);

        /// <summary>
        /// This API is used for getting Secure Payment Batch Details
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Secure Payment Batch Details Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentBatchDetailsResponse&gt;</returns>
        ApiResponse<List<PaymentBatchDetailsResponse>> SecureBatchesDetailsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0);
        /// <summary>
        /// This API execute on-demand batch transaction.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureBatchExecuteRequest">Payment Batch Execution Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void SecureBatchesExecutePost(string xApiKey, string xAppKey, float xVersion, string origin, SecureBatchExecuteRequest secureBatchExecuteRequest, int operationIndex = 0);

        /// <summary>
        /// This API execute on-demand batch transaction.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureBatchExecuteRequest">Payment Batch Execution Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> SecureBatchesExecutePostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecureBatchExecuteRequest secureBatchExecuteRequest, int operationIndex = 0);
        /// <summary>
        /// This API is used for getting Secure Payment Batches
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="startRow">Set StartRow (optional)</param>
        /// <param name="pageSize">Set PageSize (optional)</param>
        /// <param name="sortField">Set SortField (optional)</param>
        /// <param name="asc">Set Asc (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentBatchResponse</returns>
        PaymentBatchResponse SecureBatchesPost(string xApiKey, string xAppKey, float xVersion, string origin, float? startRow = default(float?), float? pageSize = default(float?), string? sortField = default(string?), bool? asc = default(bool?), int operationIndex = 0);

        /// <summary>
        /// This API is used for getting Secure Payment Batches
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="startRow">Set StartRow (optional)</param>
        /// <param name="pageSize">Set PageSize (optional)</param>
        /// <param name="sortField">Set SortField (optional)</param>
        /// <param name="asc">Set Asc (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentBatchResponse</returns>
        ApiResponse<PaymentBatchResponse> SecureBatchesPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, float? startRow = default(float?), float? pageSize = default(float?), string? sortField = default(string?), bool? asc = default(bool?), int operationIndex = 0);
        /// <summary>
        /// This API will returns batch timeline.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Payment Batch Timeline Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentBatchEventLogResponse&gt;</returns>
        List<PaymentBatchEventLogResponse> SecureBatchesTimelinesPost(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0);

        /// <summary>
        /// This API will returns batch timeline.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Payment Batch Timeline Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentBatchEventLogResponse&gt;</returns>
        ApiResponse<List<PaymentBatchEventLogResponse>> SecureBatchesTimelinesPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0);
        /// <summary>
        /// This API cancels transactions from an active batch.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentBatchCancellationRequest">Payment Batch Cancellation Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void SecureBatchesTransactionsCancelPost(string xApiKey, string xAppKey, float xVersion, string origin, PaymentBatchCancellationRequest paymentBatchCancellationRequest, int operationIndex = 0);

        /// <summary>
        /// This API cancels transactions from an active batch.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentBatchCancellationRequest">Payment Batch Cancellation Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> SecureBatchesTransactionsCancelPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, PaymentBatchCancellationRequest paymentBatchCancellationRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecurePaymentBatchingApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// This API is used for getting Secure Payment Batch Details
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Secure Payment Batch Details Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentBatchDetailsResponse&gt;</returns>
        System.Threading.Tasks.Task<List<PaymentBatchDetailsResponse>> SecureBatchesDetailsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API is used for getting Secure Payment Batch Details
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Secure Payment Batch Details Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentBatchDetailsResponse&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PaymentBatchDetailsResponse>>> SecureBatchesDetailsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// This API execute on-demand batch transaction.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureBatchExecuteRequest">Payment Batch Execution Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task SecureBatchesExecutePostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureBatchExecuteRequest secureBatchExecuteRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API execute on-demand batch transaction.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureBatchExecuteRequest">Payment Batch Execution Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SecureBatchesExecutePostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureBatchExecuteRequest secureBatchExecuteRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// This API is used for getting Secure Payment Batches
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="startRow">Set StartRow (optional)</param>
        /// <param name="pageSize">Set PageSize (optional)</param>
        /// <param name="sortField">Set SortField (optional)</param>
        /// <param name="asc">Set Asc (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentBatchResponse</returns>
        System.Threading.Tasks.Task<PaymentBatchResponse> SecureBatchesPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, float? startRow = default(float?), float? pageSize = default(float?), string? sortField = default(string?), bool? asc = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API is used for getting Secure Payment Batches
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="startRow">Set StartRow (optional)</param>
        /// <param name="pageSize">Set PageSize (optional)</param>
        /// <param name="sortField">Set SortField (optional)</param>
        /// <param name="asc">Set Asc (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentBatchResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentBatchResponse>> SecureBatchesPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, float? startRow = default(float?), float? pageSize = default(float?), string? sortField = default(string?), bool? asc = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// This API will returns batch timeline.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Payment Batch Timeline Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentBatchEventLogResponse&gt;</returns>
        System.Threading.Tasks.Task<List<PaymentBatchEventLogResponse>> SecureBatchesTimelinesPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API will returns batch timeline.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Payment Batch Timeline Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentBatchEventLogResponse&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PaymentBatchEventLogResponse>>> SecureBatchesTimelinesPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// This API cancels transactions from an active batch.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentBatchCancellationRequest">Payment Batch Cancellation Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task SecureBatchesTransactionsCancelPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, PaymentBatchCancellationRequest paymentBatchCancellationRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API cancels transactions from an active batch.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentBatchCancellationRequest">Payment Batch Cancellation Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SecureBatchesTransactionsCancelPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, PaymentBatchCancellationRequest paymentBatchCancellationRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecurePaymentBatchingApi : ISecurePaymentBatchingApiSync, ISecurePaymentBatchingApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SecurePaymentBatchingApi : ISecurePaymentBatchingApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurePaymentBatchingApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecurePaymentBatchingApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurePaymentBatchingApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecurePaymentBatchingApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurePaymentBatchingApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SecurePaymentBatchingApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurePaymentBatchingApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SecurePaymentBatchingApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// This API is used for getting Secure Payment Batch Details 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Secure Payment Batch Details Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentBatchDetailsResponse&gt;</returns>
        public List<PaymentBatchDetailsResponse> SecureBatchesDetailsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<List<PaymentBatchDetailsResponse>> localVarResponse = SecureBatchesDetailsPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, securePaymentBatchDetailsRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for getting Secure Payment Batch Details 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Secure Payment Batch Details Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentBatchDetailsResponse&gt;</returns>
        public Org.OpenAPITools.Client.ApiResponse<List<PaymentBatchDetailsResponse>> SecureBatchesDetailsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesDetailsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesDetailsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesDetailsPost");
            }

            // verify the required parameter 'securePaymentBatchDetailsRequest' is set
            if (securePaymentBatchDetailsRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'securePaymentBatchDetailsRequest' when calling SecurePaymentBatchingApi->SecureBatchesDetailsPost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = securePaymentBatchDetailsRequest;

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesDetailsPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<List<PaymentBatchDetailsResponse>>("/secure/batches/details", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesDetailsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used for getting Secure Payment Batch Details 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Secure Payment Batch Details Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentBatchDetailsResponse&gt;</returns>
        public async System.Threading.Tasks.Task<List<PaymentBatchDetailsResponse>> SecureBatchesDetailsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<List<PaymentBatchDetailsResponse>> localVarResponse = await SecureBatchesDetailsPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, securePaymentBatchDetailsRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for getting Secure Payment Batch Details 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Secure Payment Batch Details Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentBatchDetailsResponse&gt;)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<List<PaymentBatchDetailsResponse>>> SecureBatchesDetailsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesDetailsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesDetailsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesDetailsPost");
            }

            // verify the required parameter 'securePaymentBatchDetailsRequest' is set
            if (securePaymentBatchDetailsRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'securePaymentBatchDetailsRequest' when calling SecurePaymentBatchingApi->SecureBatchesDetailsPost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = securePaymentBatchDetailsRequest;

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesDetailsPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<List<PaymentBatchDetailsResponse>>("/secure/batches/details", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesDetailsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API execute on-demand batch transaction. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureBatchExecuteRequest">Payment Batch Execution Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void SecureBatchesExecutePost(string xApiKey, string xAppKey, float xVersion, string origin, SecureBatchExecuteRequest secureBatchExecuteRequest, int operationIndex = 0)
        {
            SecureBatchesExecutePostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, secureBatchExecuteRequest);
        }

        /// <summary>
        /// This API execute on-demand batch transaction. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureBatchExecuteRequest">Payment Batch Execution Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> SecureBatchesExecutePostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecureBatchExecuteRequest secureBatchExecuteRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesExecutePost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesExecutePost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesExecutePost");
            }

            // verify the required parameter 'secureBatchExecuteRequest' is set
            if (secureBatchExecuteRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'secureBatchExecuteRequest' when calling SecurePaymentBatchingApi->SecureBatchesExecutePost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = secureBatchExecuteRequest;

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesExecutePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/secure/batches/execute", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesExecutePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API execute on-demand batch transaction. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureBatchExecuteRequest">Payment Batch Execution Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task SecureBatchesExecutePostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureBatchExecuteRequest secureBatchExecuteRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await SecureBatchesExecutePostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, secureBatchExecuteRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// This API execute on-demand batch transaction. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureBatchExecuteRequest">Payment Batch Execution Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> SecureBatchesExecutePostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureBatchExecuteRequest secureBatchExecuteRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesExecutePost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesExecutePost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesExecutePost");
            }

            // verify the required parameter 'secureBatchExecuteRequest' is set
            if (secureBatchExecuteRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'secureBatchExecuteRequest' when calling SecurePaymentBatchingApi->SecureBatchesExecutePost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = secureBatchExecuteRequest;

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesExecutePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/secure/batches/execute", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesExecutePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used for getting Secure Payment Batches 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="startRow">Set StartRow (optional)</param>
        /// <param name="pageSize">Set PageSize (optional)</param>
        /// <param name="sortField">Set SortField (optional)</param>
        /// <param name="asc">Set Asc (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentBatchResponse</returns>
        public PaymentBatchResponse SecureBatchesPost(string xApiKey, string xAppKey, float xVersion, string origin, float? startRow = default(float?), float? pageSize = default(float?), string? sortField = default(string?), bool? asc = default(bool?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<PaymentBatchResponse> localVarResponse = SecureBatchesPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, startRow, pageSize, sortField, asc);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for getting Secure Payment Batches 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="startRow">Set StartRow (optional)</param>
        /// <param name="pageSize">Set PageSize (optional)</param>
        /// <param name="sortField">Set SortField (optional)</param>
        /// <param name="asc">Set Asc (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentBatchResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<PaymentBatchResponse> SecureBatchesPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, float? startRow = default(float?), float? pageSize = default(float?), string? sortField = default(string?), bool? asc = default(bool?), int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesPost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (startRow != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "startRow", startRow));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (sortField != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "sortField", sortField));
            }
            if (asc != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Asc", asc));
            }
            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PaymentBatchResponse>("/secure/batches", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used for getting Secure Payment Batches 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="startRow">Set StartRow (optional)</param>
        /// <param name="pageSize">Set PageSize (optional)</param>
        /// <param name="sortField">Set SortField (optional)</param>
        /// <param name="asc">Set Asc (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentBatchResponse</returns>
        public async System.Threading.Tasks.Task<PaymentBatchResponse> SecureBatchesPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, float? startRow = default(float?), float? pageSize = default(float?), string? sortField = default(string?), bool? asc = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<PaymentBatchResponse> localVarResponse = await SecureBatchesPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, startRow, pageSize, sortField, asc, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for getting Secure Payment Batches 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="startRow">Set StartRow (optional)</param>
        /// <param name="pageSize">Set PageSize (optional)</param>
        /// <param name="sortField">Set SortField (optional)</param>
        /// <param name="asc">Set Asc (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentBatchResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<PaymentBatchResponse>> SecureBatchesPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, float? startRow = default(float?), float? pageSize = default(float?), string? sortField = default(string?), bool? asc = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesPost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (startRow != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "startRow", startRow));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (sortField != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "sortField", sortField));
            }
            if (asc != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Asc", asc));
            }
            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PaymentBatchResponse>("/secure/batches", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API will returns batch timeline. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Payment Batch Timeline Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentBatchEventLogResponse&gt;</returns>
        public List<PaymentBatchEventLogResponse> SecureBatchesTimelinesPost(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<List<PaymentBatchEventLogResponse>> localVarResponse = SecureBatchesTimelinesPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, securePaymentBatchDetailsRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API will returns batch timeline. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Payment Batch Timeline Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentBatchEventLogResponse&gt;</returns>
        public Org.OpenAPITools.Client.ApiResponse<List<PaymentBatchEventLogResponse>> SecureBatchesTimelinesPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesTimelinesPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesTimelinesPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesTimelinesPost");
            }

            // verify the required parameter 'securePaymentBatchDetailsRequest' is set
            if (securePaymentBatchDetailsRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'securePaymentBatchDetailsRequest' when calling SecurePaymentBatchingApi->SecureBatchesTimelinesPost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = securePaymentBatchDetailsRequest;

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesTimelinesPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<List<PaymentBatchEventLogResponse>>("/secure/batches/timelines", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesTimelinesPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API will returns batch timeline. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Payment Batch Timeline Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentBatchEventLogResponse&gt;</returns>
        public async System.Threading.Tasks.Task<List<PaymentBatchEventLogResponse>> SecureBatchesTimelinesPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<List<PaymentBatchEventLogResponse>> localVarResponse = await SecureBatchesTimelinesPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, securePaymentBatchDetailsRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API will returns batch timeline. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentBatchDetailsRequest">Payment Batch Timeline Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentBatchEventLogResponse&gt;)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<List<PaymentBatchEventLogResponse>>> SecureBatchesTimelinesPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentBatchDetailsRequest securePaymentBatchDetailsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesTimelinesPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesTimelinesPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesTimelinesPost");
            }

            // verify the required parameter 'securePaymentBatchDetailsRequest' is set
            if (securePaymentBatchDetailsRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'securePaymentBatchDetailsRequest' when calling SecurePaymentBatchingApi->SecureBatchesTimelinesPost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = securePaymentBatchDetailsRequest;

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesTimelinesPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<List<PaymentBatchEventLogResponse>>("/secure/batches/timelines", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesTimelinesPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API cancels transactions from an active batch. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentBatchCancellationRequest">Payment Batch Cancellation Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void SecureBatchesTransactionsCancelPost(string xApiKey, string xAppKey, float xVersion, string origin, PaymentBatchCancellationRequest paymentBatchCancellationRequest, int operationIndex = 0)
        {
            SecureBatchesTransactionsCancelPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, paymentBatchCancellationRequest);
        }

        /// <summary>
        /// This API cancels transactions from an active batch. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentBatchCancellationRequest">Payment Batch Cancellation Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> SecureBatchesTransactionsCancelPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, PaymentBatchCancellationRequest paymentBatchCancellationRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesTransactionsCancelPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesTransactionsCancelPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesTransactionsCancelPost");
            }

            // verify the required parameter 'paymentBatchCancellationRequest' is set
            if (paymentBatchCancellationRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'paymentBatchCancellationRequest' when calling SecurePaymentBatchingApi->SecureBatchesTransactionsCancelPost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = paymentBatchCancellationRequest;

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesTransactionsCancelPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/secure/batches/transactions/cancel", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesTransactionsCancelPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API cancels transactions from an active batch. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentBatchCancellationRequest">Payment Batch Cancellation Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task SecureBatchesTransactionsCancelPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, PaymentBatchCancellationRequest paymentBatchCancellationRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await SecureBatchesTransactionsCancelPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, paymentBatchCancellationRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// This API cancels transactions from an active batch. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentBatchCancellationRequest">Payment Batch Cancellation Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> SecureBatchesTransactionsCancelPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, PaymentBatchCancellationRequest paymentBatchCancellationRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentBatchingApi->SecureBatchesTransactionsCancelPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentBatchingApi->SecureBatchesTransactionsCancelPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentBatchingApi->SecureBatchesTransactionsCancelPost");
            }

            // verify the required parameter 'paymentBatchCancellationRequest' is set
            if (paymentBatchCancellationRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'paymentBatchCancellationRequest' when calling SecurePaymentBatchingApi->SecureBatchesTransactionsCancelPost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = paymentBatchCancellationRequest;

            localVarRequestOptions.Operation = "SecurePaymentBatchingApi.SecureBatchesTransactionsCancelPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (x-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (x-app-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-app-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-app-key", this.Configuration.GetApiKeyWithPrefix("x-app-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/secure/batches/transactions/cancel", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureBatchesTransactionsCancelPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
