/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentResponseDto
        //private PaymentResponseDto instance;

        public PaymentResponseDtoTests()
        {
            // TODO uncomment below to create an instance of PaymentResponseDto
            //instance = new PaymentResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentResponseDto
        /// </summary>
        [Fact]
        public void PaymentResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentResponseDto
            //Assert.IsType<PaymentResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Fact]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }

        /// <summary>
        /// Test the property 'VendorId'
        /// </summary>
        [Fact]
        public void VendorIdTest()
        {
            // TODO unit test for the property 'VendorId'
        }

        /// <summary>
        /// Test the property 'PaymentStatus'
        /// </summary>
        [Fact]
        public void PaymentStatusTest()
        {
            // TODO unit test for the property 'PaymentStatus'
        }

        /// <summary>
        /// Test the property 'PaymentMethodStatus'
        /// </summary>
        [Fact]
        public void PaymentMethodStatusTest()
        {
            // TODO unit test for the property 'PaymentMethodStatus'
        }

        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'BankAccountDetails'
        /// </summary>
        [Fact]
        public void BankAccountDetailsTest()
        {
            // TODO unit test for the property 'BankAccountDetails'
        }

        /// <summary>
        /// Test the property 'VendorAddress'
        /// </summary>
        [Fact]
        public void VendorAddressTest()
        {
            // TODO unit test for the property 'VendorAddress'
        }
    }
}
