/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentRequestTenderInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentRequestTenderInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentRequestTenderInfo
        //private PaymentRequestTenderInfo instance;

        public PaymentRequestTenderInfoTests()
        {
            // TODO uncomment below to create an instance of PaymentRequestTenderInfo
            //instance = new PaymentRequestTenderInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentRequestTenderInfo
        /// </summary>
        [Fact]
        public void PaymentRequestTenderInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentRequestTenderInfo
            //Assert.IsType<PaymentRequestTenderInfo>(instance);
        }

        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Fact]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }

        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }

        /// <summary>
        /// Test the property 'RoutingNumber'
        /// </summary>
        [Fact]
        public void RoutingNumberTest()
        {
            // TODO unit test for the property 'RoutingNumber'
        }

        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }

        /// <summary>
        /// Test the property 'CheckNumber'
        /// </summary>
        [Fact]
        public void CheckNumberTest()
        {
            // TODO unit test for the property 'CheckNumber'
        }

        /// <summary>
        /// Test the property 'AccountCategory'
        /// </summary>
        [Fact]
        public void AccountCategoryTest()
        {
            // TODO unit test for the property 'AccountCategory'
        }

        /// <summary>
        /// Test the property 'AccountHolderName'
        /// </summary>
        [Fact]
        public void AccountHolderNameTest()
        {
            // TODO unit test for the property 'AccountHolderName'
        }

        /// <summary>
        /// Test the property 'NameOnCheck'
        /// </summary>
        [Fact]
        public void NameOnCheckTest()
        {
            // TODO unit test for the property 'NameOnCheck'
        }

        /// <summary>
        /// Test the property 'CardHolderName'
        /// </summary>
        [Fact]
        public void CardHolderNameTest()
        {
            // TODO unit test for the property 'CardHolderName'
        }

        /// <summary>
        /// Test the property 'CardType'
        /// </summary>
        [Fact]
        public void CardTypeTest()
        {
            // TODO unit test for the property 'CardType'
        }

        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Fact]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }

        /// <summary>
        /// Test the property 'CardExpiry'
        /// </summary>
        [Fact]
        public void CardExpiryTest()
        {
            // TODO unit test for the property 'CardExpiry'
        }

        /// <summary>
        /// Test the property 'Cvv'
        /// </summary>
        [Fact]
        public void CvvTest()
        {
            // TODO unit test for the property 'Cvv'
        }

        /// <summary>
        /// Test the property 'CvDataStatus'
        /// </summary>
        [Fact]
        public void CvDataStatusTest()
        {
            // TODO unit test for the property 'CvDataStatus'
        }

        /// <summary>
        /// Test the property 'TrackData'
        /// </summary>
        [Fact]
        public void TrackDataTest()
        {
            // TODO unit test for the property 'TrackData'
        }

        /// <summary>
        /// Test the property 'RemoveDiscounting'
        /// </summary>
        [Fact]
        public void RemoveDiscountingTest()
        {
            // TODO unit test for the property 'RemoveDiscounting'
        }

        /// <summary>
        /// Test the property 'SuppressCommission'
        /// </summary>
        [Fact]
        public void SuppressCommissionTest()
        {
            // TODO unit test for the property 'SuppressCommission'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'ConvenienceAmount'
        /// </summary>
        [Fact]
        public void ConvenienceAmountTest()
        {
            // TODO unit test for the property 'ConvenienceAmount'
        }

        /// <summary>
        /// Test the property 'PreAuthCode'
        /// </summary>
        [Fact]
        public void PreAuthCodeTest()
        {
            // TODO unit test for the property 'PreAuthCode'
        }

        /// <summary>
        /// Test the property 'CreateAccountToken'
        /// </summary>
        [Fact]
        public void CreateAccountTokenTest()
        {
            // TODO unit test for the property 'CreateAccountToken'
        }

        /// <summary>
        /// Test the property 'AccountToken'
        /// </summary>
        [Fact]
        public void AccountTokenTest()
        {
            // TODO unit test for the property 'AccountToken'
        }
    }
}
