/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PFLiteGenerateQuoteResponseItemESignResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PFLiteGenerateQuoteResponseItemESignResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PFLiteGenerateQuoteResponseItemESignResult
        //private PFLiteGenerateQuoteResponseItemESignResult instance;

        public PFLiteGenerateQuoteResponseItemESignResultTests()
        {
            // TODO uncomment below to create an instance of PFLiteGenerateQuoteResponseItemESignResult
            //instance = new PFLiteGenerateQuoteResponseItemESignResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PFLiteGenerateQuoteResponseItemESignResult
        /// </summary>
        [Fact]
        public void PFLiteGenerateQuoteResponseItemESignResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" PFLiteGenerateQuoteResponseItemESignResult
            //Assert.IsType<PFLiteGenerateQuoteResponseItemESignResult>(instance);
        }

        /// <summary>
        /// Test the property 'Processed'
        /// </summary>
        [Fact]
        public void ProcessedTest()
        {
            // TODO unit test for the property 'Processed'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'BatchId'
        /// </summary>
        [Fact]
        public void BatchIdTest()
        {
            // TODO unit test for the property 'BatchId'
        }

        /// <summary>
        /// Test the property 'AgentUrl'
        /// </summary>
        [Fact]
        public void AgentUrlTest()
        {
            // TODO unit test for the property 'AgentUrl'
        }

        /// <summary>
        /// Test the property 'InsuredUrl'
        /// </summary>
        [Fact]
        public void InsuredUrlTest()
        {
            // TODO unit test for the property 'InsuredUrl'
        }

        /// <summary>
        /// Test the property 'ESignOption'
        /// </summary>
        [Fact]
        public void ESignOptionTest()
        {
            // TODO unit test for the property 'ESignOption'
        }
    }
}
