/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PFLitePaymentLinkRequestSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PFLitePaymentLinkRequestSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PFLitePaymentLinkRequestSettings
        //private PFLitePaymentLinkRequestSettings instance;

        public PFLitePaymentLinkRequestSettingsTests()
        {
            // TODO uncomment below to create an instance of PFLitePaymentLinkRequestSettings
            //instance = new PFLitePaymentLinkRequestSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PFLitePaymentLinkRequestSettings
        /// </summary>
        [Fact]
        public void PFLitePaymentLinkRequestSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PFLitePaymentLinkRequestSettings
            //Assert.IsType<PFLitePaymentLinkRequestSettings>(instance);
        }

        /// <summary>
        /// Test the property 'SelectedCustomerFields'
        /// </summary>
        [Fact]
        public void SelectedCustomerFieldsTest()
        {
            // TODO unit test for the property 'SelectedCustomerFields'
        }

        /// <summary>
        /// Test the property 'AdditionalDetailsPreference'
        /// </summary>
        [Fact]
        public void AdditionalDetailsPreferenceTest()
        {
            // TODO unit test for the property 'AdditionalDetailsPreference'
        }

        /// <summary>
        /// Test the property 'Intent'
        /// </summary>
        [Fact]
        public void IntentTest()
        {
            // TODO unit test for the property 'Intent'
        }
    }
}
