/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PFLiteGenerateQuoteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PFLiteGenerateQuoteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PFLiteGenerateQuoteResponse
        //private PFLiteGenerateQuoteResponse instance;

        public PFLiteGenerateQuoteResponseTests()
        {
            // TODO uncomment below to create an instance of PFLiteGenerateQuoteResponse
            //instance = new PFLiteGenerateQuoteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PFLiteGenerateQuoteResponse
        /// </summary>
        [Fact]
        public void PFLiteGenerateQuoteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PFLiteGenerateQuoteResponse
            //Assert.IsType<PFLiteGenerateQuoteResponse>(instance);
        }

        /// <summary>
        /// Test the property 'IsSuccess'
        /// </summary>
        [Fact]
        public void IsSuccessTest()
        {
            // TODO unit test for the property 'IsSuccess'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'IntegrationID'
        /// </summary>
        [Fact]
        public void IntegrationIDTest()
        {
            // TODO unit test for the property 'IntegrationID'
        }

        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }
    }
}
