/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RefundEligibility
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RefundEligibilityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RefundEligibility
        //private RefundEligibility instance;

        public RefundEligibilityTests()
        {
            // TODO uncomment below to create an instance of RefundEligibility
            //instance = new RefundEligibility();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RefundEligibility
        /// </summary>
        [Fact]
        public void RefundEligibilityInstanceTest()
        {
            // TODO uncomment below to test "IsType" RefundEligibility
            //Assert.IsType<RefundEligibility>(instance);
        }

        /// <summary>
        /// Test the property 'RefundEligible'
        /// </summary>
        [Fact]
        public void RefundEligibleTest()
        {
            // TODO unit test for the property 'RefundEligible'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
