/*
 * Secure API
 *
 * Secure API's
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SecurePaymentDetailsResponseTransactionEntitySplitResponsesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecurePaymentDetailsResponseTransactionEntitySplitResponsesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SecurePaymentDetailsResponseTransactionEntitySplitResponsesInner
        //private SecurePaymentDetailsResponseTransactionEntitySplitResponsesInner instance;

        public SecurePaymentDetailsResponseTransactionEntitySplitResponsesInnerTests()
        {
            // TODO uncomment below to create an instance of SecurePaymentDetailsResponseTransactionEntitySplitResponsesInner
            //instance = new SecurePaymentDetailsResponseTransactionEntitySplitResponsesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecurePaymentDetailsResponseTransactionEntitySplitResponsesInner
        /// </summary>
        [Fact]
        public void SecurePaymentDetailsResponseTransactionEntitySplitResponsesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SecurePaymentDetailsResponseTransactionEntitySplitResponsesInner
            //Assert.IsType<SecurePaymentDetailsResponseTransactionEntitySplitResponsesInner>(instance);
        }

        /// <summary>
        /// Test the property 'AccountAlias'
        /// </summary>
        [Fact]
        public void AccountAliasTest()
        {
            // TODO unit test for the property 'AccountAlias'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'ChargeIndicator'
        /// </summary>
        [Fact]
        public void ChargeIndicatorTest()
        {
            // TODO unit test for the property 'ChargeIndicator'
        }
    }
}
