/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SecureVendorStatusRequestDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecureVendorStatusRequestDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SecureVendorStatusRequestDTO
        //private SecureVendorStatusRequestDTO instance;

        public SecureVendorStatusRequestDTOTests()
        {
            // TODO uncomment below to create an instance of SecureVendorStatusRequestDTO
            //instance = new SecureVendorStatusRequestDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureVendorStatusRequestDTO
        /// </summary>
        [Fact]
        public void SecureVendorStatusRequestDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" SecureVendorStatusRequestDTO
            //Assert.IsType<SecureVendorStatusRequestDTO>(instance);
        }

        /// <summary>
        /// Test the property 'VendorId'
        /// </summary>
        [Fact]
        public void VendorIdTest()
        {
            // TODO unit test for the property 'VendorId'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
    }
}
