/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SecureMerchantTokenShortResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecureMerchantTokenShortResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SecureMerchantTokenShortResponse
        //private SecureMerchantTokenShortResponse instance;

        public SecureMerchantTokenShortResponseTests()
        {
            // TODO uncomment below to create an instance of SecureMerchantTokenShortResponse
            //instance = new SecureMerchantTokenShortResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureMerchantTokenShortResponse
        /// </summary>
        [Fact]
        public void SecureMerchantTokenShortResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SecureMerchantTokenShortResponse
            //Assert.IsType<SecureMerchantTokenShortResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'TokenLinkId'
        /// </summary>
        [Fact]
        public void TokenLinkIdTest()
        {
            // TODO unit test for the property 'TokenLinkId'
        }

        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Fact]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }

        /// <summary>
        /// Test the property 'SelfToken'
        /// </summary>
        [Fact]
        public void SelfTokenTest()
        {
            // TODO unit test for the property 'SelfToken'
        }

        /// <summary>
        /// Test the property 'TokenProvider'
        /// </summary>
        [Fact]
        public void TokenProviderTest()
        {
            // TODO unit test for the property 'TokenProvider'
        }

        /// <summary>
        /// Test the property 'AccountHolderName'
        /// </summary>
        [Fact]
        public void AccountHolderNameTest()
        {
            // TODO unit test for the property 'AccountHolderName'
        }

        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Fact]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }

        /// <summary>
        /// Test the property 'CardExpiry'
        /// </summary>
        [Fact]
        public void CardExpiryTest()
        {
            // TODO unit test for the property 'CardExpiry'
        }

        /// <summary>
        /// Test the property 'RoutingNumber'
        /// </summary>
        [Fact]
        public void RoutingNumberTest()
        {
            // TODO unit test for the property 'RoutingNumber'
        }

        /// <summary>
        /// Test the property 'MaskedAccountNumber'
        /// </summary>
        [Fact]
        public void MaskedAccountNumberTest()
        {
            // TODO unit test for the property 'MaskedAccountNumber'
        }

        /// <summary>
        /// Test the property 'ProcessMethod'
        /// </summary>
        [Fact]
        public void ProcessMethodTest()
        {
            // TODO unit test for the property 'ProcessMethod'
        }

        /// <summary>
        /// Test the property 'ChannelType'
        /// </summary>
        [Fact]
        public void ChannelTypeTest()
        {
            // TODO unit test for the property 'ChannelType'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
    }
}
