/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TokenLinkSecureRequestCallbackParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenLinkSecureRequestCallbackParametersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenLinkSecureRequestCallbackParameters
        //private TokenLinkSecureRequestCallbackParameters instance;

        public TokenLinkSecureRequestCallbackParametersTests()
        {
            // TODO uncomment below to create an instance of TokenLinkSecureRequestCallbackParameters
            //instance = new TokenLinkSecureRequestCallbackParameters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenLinkSecureRequestCallbackParameters
        /// </summary>
        [Fact]
        public void TokenLinkSecureRequestCallbackParametersInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenLinkSecureRequestCallbackParameters
            //Assert.IsType<TokenLinkSecureRequestCallbackParameters>(instance);
        }

        /// <summary>
        /// Test the property 'CallbackSuccessUrl'
        /// </summary>
        [Fact]
        public void CallbackSuccessUrlTest()
        {
            // TODO unit test for the property 'CallbackSuccessUrl'
        }

        /// <summary>
        /// Test the property 'CallbackFailureUrl'
        /// </summary>
        [Fact]
        public void CallbackFailureUrlTest()
        {
            // TODO unit test for the property 'CallbackFailureUrl'
        }

        /// <summary>
        /// Test the property 'AccessKey'
        /// </summary>
        [Fact]
        public void AccessKeyTest()
        {
            // TODO unit test for the property 'AccessKey'
        }

        /// <summary>
        /// Test the property 'SecretKey'
        /// </summary>
        [Fact]
        public void SecretKeyTest()
        {
            // TODO unit test for the property 'SecretKey'
        }

        /// <summary>
        /// Test the property 'ReferenceNo'
        /// </summary>
        [Fact]
        public void ReferenceNoTest()
        {
            // TODO unit test for the property 'ReferenceNo'
        }

        /// <summary>
        /// Test the property 'ReferenceType'
        /// </summary>
        [Fact]
        public void ReferenceTypeTest()
        {
            // TODO unit test for the property 'ReferenceType'
        }

        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }

        /// <summary>
        /// Test the property 'CallbackApiUrl'
        /// </summary>
        [Fact]
        public void CallbackApiUrlTest()
        {
            // TODO unit test for the property 'CallbackApiUrl'
        }

        /// <summary>
        /// Test the property 'CallbackMessage'
        /// </summary>
        [Fact]
        public void CallbackMessageTest()
        {
            // TODO unit test for the property 'CallbackMessage'
        }

        /// <summary>
        /// Test the property 'RedirectionTime'
        /// </summary>
        [Fact]
        public void RedirectionTimeTest()
        {
            // TODO unit test for the property 'RedirectionTime'
        }
    }
}
