/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionDetailResponseRefundTransactions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionDetailResponseRefundTransactionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionDetailResponseRefundTransactions
        //private TransactionDetailResponseRefundTransactions instance;

        public TransactionDetailResponseRefundTransactionsTests()
        {
            // TODO uncomment below to create an instance of TransactionDetailResponseRefundTransactions
            //instance = new TransactionDetailResponseRefundTransactions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionDetailResponseRefundTransactions
        /// </summary>
        [Fact]
        public void TransactionDetailResponseRefundTransactionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionDetailResponseRefundTransactions
            //Assert.IsType<TransactionDetailResponseRefundTransactions>(instance);
        }

        /// <summary>
        /// Test the property 'TotalRowCounts'
        /// </summary>
        [Fact]
        public void TotalRowCountsTest()
        {
            // TODO unit test for the property 'TotalRowCounts'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
